import React from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import InvoiceTable from "./InvoiceTable";
import { Filters } from "./_Filters/Filters";

export const metadata: Metadata = {
  title: "Invoices",
  description: "Generated by create next app",
};

export default async function Invoices() {
  return (
    <ContentWrapper>
      <div className="top-title">
        <h2 className="f-22 bold mb-4">Invoice</h2>
      </div>
      <div className="invoices-filters">
        <Filters />
      </div>
      <InvoiceTable />
    </ContentWrapper>
  );
}
