import { PaginateData } from "@/types/Paginate";
import { User as UserType } from "@/types/User";
import db from "@/utils/connectDB";
import { Metadata } from "next";
import React from "react";
import ClaimFinalcialForm from "./_ClaimReportForm";
import "../../admin/admin.css";
import LawyerFinancialForm from "./_LawyerFinancialForm";
import ClaimFinancialModel from "@/models/claim_financial.model";

export const metadata: Metadata = {
  title: "Claim Financial Report",
  description: "Generated by create next app",
};

export default async function ClaimFinalcialReport({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  let id: string | string[] | undefined | number = searchParams?.id;
  let type: string | string[] | undefined | number = searchParams?.type;

  const fetchData = async () => {
    await db.connectDB();
    const reportData = await ClaimFinancialModel.findOne({ case_id: id });
    return reportData;
  };
  const data = await fetchData();
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">
          {type === "lawyer" ? "Lawyer" : "Claim"} Financial Report
        </h2>
      </div>
      <div className="res-table-box">
        <div className="mt-4">
          {type === "lawyer" ? (
            <LawyerFinancialForm case_id={id} data={data} />
          ) : (
            <ClaimFinalcialForm case_id={id} data={data} />
          )}
        </div>
      </div>
    </div>
  );
}
