"use client";

import React, { useEffect, useState } from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import "../../client/client.css";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import PrivacyPolicy from "./privacy-policy/Privacy";
import ThankuStep from "./thanku-page/page";
import RoleBasicInformation from "./_WrongfulClaimsForms/RoleBasicInformation";
import AboutYourself from "./_WrongfulClaimsForms/AboutYourself";
import EmployeeDetails from "./_WrongfulClaimsForms/EmployeeDetails";
import TerminationDetails from "./_WrongfulClaimsForms/TerminationDetails";
import SupportingEvidence from "./_WrongfulClaimsForms/SupportingEvidence";
import { useSearchParams, useRouter } from "next/navigation";
import LinearProgress, {
  LinearProgressProps,
} from "@mui/material/LinearProgress";
import axios from "axios";

import CircularProgress from "@mui/material/CircularProgress";
import { Wrongful } from "@/types/Wrongful";
import HealthStatus from "./_WrongfulClaimsForms/HealthStatus";
import ImpactEvidence from "./_WrongfulClaimsForms/Impact&Evidence";
import ReviewForm from "./_WrongfulClaimsForms/ReviewForm";

// export const metadata: Metadata = {
//   title: "Eviction Assessment Form",
//   description: "Generated by create next app",
// };

// Wrongful Termination Claims Assessment Form

export default function WrongfulTerminationClaims() {
  const router = useRouter();

  const [progress, setProgress] = useState(10);

  const [loading, setLoading] = useState(false);

  const [wrongfulData, setWrongfulData] = useState<Wrongful>();

  const searchParmas = useSearchParams();
  const progressFromQuery = searchParmas?.get("progress");
  const caseFromQuery = searchParmas?.get("caseId");

  function LinearProgressWithLabel(
    props: LinearProgressProps & { value: number }
  ) {
    return (
      <Box sx={{ display: "flex", alignItems: "center" }}>
        <Box sx={{ width: "100%", mr: 1 }}>
          <LinearProgress variant="determinate" {...props} />
        </Box>
      </Box>
    );
  }

  useEffect(() => {
    if (progressFromQuery) {
      setProgress(+progressFromQuery);
    }
  }, [progressFromQuery]);

  useEffect(() => {
    const getCaseById = async () => {
      try {
        setLoading(true);
        if (caseFromQuery) {
          const { data } = await axios.get(
            `/api/client/category/wrongful/getWrongful?caseId=${caseFromQuery}`
          );
          if (data?.data) {
            setProgress(data?.data?.progress);
            setWrongfulData(data.data);
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", data?.data?.caseId);
            searchParmas.set("progress", data?.data?.progress);
            router.push(
              `/client/wrongful-termination?${searchParmas.toString()}`
            );
          } else {
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", caseFromQuery);
            searchParmas.set("progress", "10");
            router.push(
              `/client/wrongful-termination?${searchParmas.toString()}`
            );
          }
        }
        setLoading(false);
      } catch (error) {
        console.log("err", error);
        setLoading(false);
      }
    };
    getCaseById();
  }, [caseFromQuery, progressFromQuery]);

  const handleNext = async () => {
    try {
      if (progress === 10) {
        setLoading(true);
        let id;
        if (wrongfulData) {
          if (wrongfulData.caseId === caseFromQuery) {
            const { data } = await axios.post(
              "/api/client/category/wrongful/createWrongful",
              {
                caseId: caseFromQuery,
                progress: 20,
                nextProgress: 20,
              }
            );
            id = data.data.caseId;
          }
        } else {
          const { data } = await axios.post(
            "/api/client/category/wrongful/createWrongful",
            {
              caseId: caseFromQuery,
              progress: 20,
              nextProgress: 20,
            }
          );
          id = data.data.caseId;
        }
        const searchParmas = new URLSearchParams();
        searchParmas.set("caseId", id);
        searchParmas.set("progress", "20");
        router.push(`/client/wrongful-termination?${searchParmas.toString()}`);
        setLoading(false);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const normalise = (value: number, MAX: number) => {
    let MIN = 0;
    let finalVal = ((value - MIN) * 100) / (MAX - MIN);
    if (finalVal > 100) {
      finalVal = 100;
    }
    return finalVal;
  };
  return (
    <ContentWrapper>
      <Box sx={{ width: "100%" }}>
        <div className="top-title">
          <h2 className="f-22 bold mb-4 mt-5">
            Wrongful Termination Claims Assessment Form
          </h2>
        </div>
        <div className="white-card create-cases mt-4">
          <Box sx={{ width: "100%" }}>
            <LinearProgressWithLabel value={normalise(progress, 100)} />
          </Box>

          {loading ? (
            <div className="text-center mt-5">
              <CircularProgress />
            </div>
          ) : (
            <div>
              {
                <React.Fragment>
                  <div className="cases-active">
                    {progress === 10 && (
                      <div className="">
                        <PrivacyPolicy handleNext={handleNext} />
                      </div>
                    )}

                    {progress === 20 && (
                      <div className="">
                        <RoleBasicInformation
                          data={wrongfulData}
                          hide={false}
                        />
                      </div>
                    )}

                    {progress === 30 && (
                      <>
                        <div className=" eviction-form ">
                          <AboutYourself data={wrongfulData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 40 && (
                      <>
                        <div className=" eviction-form ">
                          <EmployeeDetails data={wrongfulData} hide={false} />
                        </div>
                      </>
                    )}
                    {progress === 50 && (
                      <>
                        <div className=" eviction-form ">
                          <HealthStatus data={wrongfulData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 60 && (
                      <>
                        <div className=" eviction-form ">
                          <TerminationDetails
                            data={wrongfulData}
                            hide={false}
                          />
                        </div>
                      </>
                    )}

                    {progress === 70 && (
                      <>
                        <div className=" eviction-form ">
                          <SupportingEvidence
                            data={wrongfulData}
                            hide={false}
                          />
                        </div>
                      </>
                    )}

                    {progress === 80 && (
                      <>
                        <div className=" eviction-form ">
                          <ImpactEvidence data={wrongfulData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 90 && (
                      <>
                        <div className=" eviction-form ">
                          <ReviewForm data={wrongfulData} />
                        </div>
                      </>
                    )}

                    {progress === 100 && (
                      <>
                        <div className=" eviction-form ">
                          <ThankuStep />
                        </div>
                      </>
                    )}
                  </div>
                </React.Fragment>
              }
            </div>
          )}
        </div>
      </Box>
    </ContentWrapper>
  );
}
