import { PaginateData } from "@/types/Paginate";
import { User as UserType } from "@/types/User";
import db from "@/utils/connectDB";
import { Metadata } from "next";
import { NextRequest } from "next/server";
import React from "react";
import Link from "next/link";
import Image from "next/image";
import "../../admin/admin.css";
import ManagersTable from "./_ManagersTable";
import Expert from "@/models/expert.model";

export const metadata: Metadata = {
  title: "Case Managers",
  description: "Generated by create next app",
};

export default async function CaseManagers({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  let page: string | string[] | undefined | number = searchParams?.page;
  page = !!page ? +page : 1;
  const fetchData = async (
    pageNumber: number
  ): Promise<PaginateData<UserType>> => {
    await db.connectDB();
    const totalUsers = await Expert.countDocuments({ isDeleted: false });
    const totalPages = Math.ceil(totalUsers / 10);
    if (pageNumber > totalPages) {
      pageNumber = totalPages;
    }
    const start = pageNumber - 1;

    const userData = await Expert.find({ isDeleted: false })
      .limit(10)
      .skip(start * 10);
    return {
      data: userData,
      currentPage: pageNumber,
      totalEntries: totalUsers,
    };
  };

  const data = await fetchData(page);

  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Case Managers</h2>
      </div>
      {/* <CaseFilters /> */}
      <div className="res-table-box">
        <div className="table-responsive mt-4">
          <ManagersTable data={data} />
        </div>
      </div>
    </div>
  );
}
