import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import UploadDoc from "./_RequestComponent/UploadDoc";
import { Button } from "@mui/material";

export const metadata: Metadata = {
  title: "Request Document Upload",
  description: "Generated by create next app",
};

export default function RequestDocumentUpload() {
  return (
    <div className="main-content expert-cases case-members request-doc-upload">
      <div className="top-br d-flex align-items-center justify-content-between">
        <h2 className="f-24">Request Document Upload</h2>
        <div className="d-flex gap-2">
          <Button variant="contained" className="reminder-btn">
            Send Reminder
          </Button>
          <Button variant="contained" className="stop-btn">
            Stop Reminder
          </Button>
        </div>
      </div>
      <UploadDoc />
    </div>
  );
}
