"use client";

import React, { useEffect, useState } from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import "../../client/client.css";
import { Stack } from "@mui/material";
import { useSearchParams, useRouter } from "next/navigation";
import CircularProgress from "@mui/material/CircularProgress";

import Box from "@mui/material/Box";
import TerminationForm from "./TerminationForm/TerminationForm";
import SideStory from "./TerminationForm/SideStory";
import WhatTheyDid from "./TerminationForm/WhatTheyDid";
import AboutBusiness from "./TerminationForm/AboutBusiness";
import axios from "axios";
import LinearProgress, {
  LinearProgressProps,
} from "@mui/material/LinearProgress";
import PrivacyPolicy from "./privacy-policy/Privacy";
import ThankYou from "./thank-you/page";
import { Sudden } from "@/types/Sudden";
import Review from "./TerminationForm/Review";

const steps = ["", "", ""];

// export const metadata: Metadata = {
//   title: "Eviction Assessment Form",
//   description: "Generated by create next app",
// };

export default function SuddenContractTermination() {
  const router = useRouter();

  const [progress, setProgress] = useState(10);

  const [loading, setLoading] = useState(false);

  const [suddenData, setSuddenData] = useState<Sudden>();

  const searchParmas = useSearchParams();
  const progressFromQuery = searchParmas?.get("progress");
  const caseFromQuery = searchParmas?.get("caseId");

  function LinearProgressWithLabel(
    props: LinearProgressProps & { value: number }
  ) {
    return (
      <Box sx={{ display: "flex", alignItems: "center" }}>
        <Box sx={{ width: "100%", mr: 1 }}>
          <LinearProgress variant="determinate" {...props} />
        </Box>
      </Box>
    );
  }

  useEffect(() => {
    if (progressFromQuery) {
      setProgress(+progressFromQuery);
    }
  }, [progressFromQuery]);

  useEffect(() => {
    const getCaseById = async () => {
      try {
        setLoading(true);
        if (caseFromQuery) {
          const { data } = await axios.get(
            `/api/client/category/sudden/getSudden?caseId=${caseFromQuery}`
          );
          console.log(data.data);
          if (data?.data) {
            setProgress(data?.data?.progress);
            setSuddenData(data.data);
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", data?.data?.caseId);
            searchParmas.set("progress", data?.data?.progress);
            router.push(
              `/client/sudden-contract-termination?${searchParmas.toString()}`
            );
          } else {
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", caseFromQuery);
            searchParmas.set("progress", "10");
            router.push(
              `/client/sudden-contract-termination?${searchParmas.toString()}`
            );
          }
        }
        setLoading(false);
      } catch (error) {
        console.log("err", error);
        setLoading(false);
      }
    };
    getCaseById();
  }, [caseFromQuery, progressFromQuery]);

  const handleNext = async () => {
    try {
      if (progress === 10) {
        setLoading(true);
        let id;
        if (suddenData) {
          if (suddenData.caseId === caseFromQuery) {
            const { data } = await axios.post(
              "/api/client/category/sudden/createSudden",
              {
                caseId: caseFromQuery,
                progress: 20,
                nextProgress: 20,
              }
            );
            id = data.data.caseId;
          }
        } else {
          const { data } = await axios.post(
            "/api/client/category/sudden/createSudden",
            {
              caseId: caseFromQuery,
              progress: 20,
              nextProgress: 20,
            }
          );
          id = data.data.caseId;
        }
        const searchParmas = new URLSearchParams();
        searchParmas.set("caseId", id);
        searchParmas.set("progress", "20");
        router.push(
          `/client/sudden-contract-termination?${searchParmas.toString()}`
        );
        setLoading(false);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const normalise = (value: number, MAX: number) => {
    let MIN = 0;
    let finalVal = ((value - MIN) * 100) / (MAX - MIN);
    if (finalVal > 100) {
      finalVal = 100;
    }
    return finalVal;
  };

  return (
    <ContentWrapper>
      <Box sx={{ width: "100%" }}>
        <div className="top-title">
          <h2 className="f-26 mb-4 fw-400  mt-5">
            SUDDEN CONTRACT TERMINATION ASSESSMENT
          </h2>
        </div>

        <div className="create-cases mt-4">
          <div className="w-100 mr-1 linear-progress-p p-1 bg-white shadow ">
            <LinearProgress
              className="green-progress-bar"
              variant="determinate"
              value={normalise(progress, 60)}
            />
          </div>
          {loading ? (
            <div className="text-center mt-5">
              <CircularProgress />
            </div>
          ) : (
            <div>
              {
                <React.Fragment>
                  <div className="cases-active">
                    {progress === 10 && (
                      <div className="">
                        <PrivacyPolicy handleNext={handleNext} />
                      </div>
                    )}

                    {progress === 20 && (
                      <div className="eviction-forms">
                        <TerminationForm data={suddenData} hide={false} />
                      </div>
                    )}

                    {progress === 30 && (
                      <>
                        <div className="eviction-forms">
                          <SideStory data={suddenData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 40 && (
                      <>
                        <div className="eviction-forms">
                          <AboutBusiness data={suddenData} hide={false} />
                        </div>
                      </>
                    )}
                    {progress === 50 && (
                      <>
                        <div className="eviction-forms">
                          <WhatTheyDid data={suddenData} hide={false} />
                        </div>
                      </>
                    )}
                    {progress === 60 && (
                      <>
                        <div className="eviction-forms">
                          <Review data={suddenData} />
                        </div>
                      </>
                    )}
                    {progress === 70 && (
                      <>
                        <div className="eviction-forms">
                          <ThankYou />
                        </div>
                      </>
                    )}
                  </div>
                </React.Fragment>
              }
            </div>
          )}
        </div>
      </Box>
    </ContentWrapper>
  );
}
