import React from "react";
import { Metadata } from "next";
import "../../client/client.css";
import { useSelectFile } from "@/hooks/useSelectFile";
import { useHookForm } from "@/hooks/useHookForm";
import { ChangePasswordForm } from "./_ChangePasswordForm";

export const metadata: Metadata = {
  title: "Change Password",
  description: "Generated by create next app",
};

export default function ChangePassword() {
  return (
    <div className="main-content expert-dashboard">
      <div className="pass-settings">
        <div className="row">
          <div className="col-12 col-md-7">
            <div className="white-card rounded-lg profile-exp-docs p-4">
              <h2 className="f-24 semi-bold">Password Settings</h2>   
              <p className="f-14 pb-3">
                Please enter your current Password to change your passsword
              </p>
              <ChangePasswordForm />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
