import React from "react";
import { Metadata } from "next";
import "../../lawyer/lawyer.css";
import { LawyerProfile } from "./_LawyerProfile";
import { useSelectFile } from "@/hooks/useSelectFile";
import { useHookForm } from "@/hooks/useHookForm";
import { LawyerImage } from "./_LawyerImage";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/Form/Button";
import idcard from "@/assets/id-card.png";
import passport from "@/assets/passport.png";
import doc from "@/assets/approve.png";

export const metadata: Metadata = {
  title: "Lawyer Profile",        
  description: "Generated by create next app",
};

export default function Profile() {
  return (
    <div className="main-content lawyer-dashboard">
      <div className="lawyer-profile client-profil">
        <div className="top-br">
          <h2 className="f-24 pb-3">Profile Settings</h2>
        </div>
        <div className="row">
            <div className="col-12 col-md-6">
              <div className="prf-card-client mb-4">
                <LawyerProfile />
              </div>
            </div>
            <div className="col-12 col-md-6">
              <div className="white-card rounded-lg  p-4">
              <div className="light-card doc-card doc-light-bg mb-4">
                <h3 className="f-18 bold pb-3">Contractual Documents</h3>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={doc} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                    Terms & Conditions
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      View
                    </Link>
                  </div>
                </div>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={doc} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                    Financing Agreement
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      View
                    </Link>
                  </div>
                </div>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={doc} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                    Mandate
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      View
                    </Link>
                  </div>
                </div>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={doc} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                    Attorney Engagement Letter
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      View
                    </Link>
                  </div>
                </div>
              </div>
              <div className="doc-pink-bg doc-card mb-4">
                <h3 className="f-18 bold pb-3">Identification Details</h3>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={idcard} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                      ID Card Document
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      Edit
                    </Link>
                  </div>
                </div>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={passport} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                      Passport Information
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      Edit
                    </Link>
                  </div>
                </div>
                <div className="uploaded-docs d-flex justify-content-between align-items-center">
                  <div className="uploaded-icon d-flex gap-2 align-items-center">
                    <div className="document-icons">
                      <Image src={doc} alt="" />
                    </div>
                    <p className="f-14 doc-name mb-0 semi-bold">
                      Residence Permit Details
                    </p>
                  </div>
                  <div className="view-docs">
                    <Link href="/" className="dark f-14 semi-bold">
                      Edit
                    </Link>
                  </div>
                </div>
                <div className="uploaded-btn mt-3 text-center">
                  <Button variant="contained" className="lawyer-btn">
                    Upload New Document
                  </Button>
                </div>
              </div>
              </div>
            </div>
          </div>
        {/* <div className="row">
          <div className="col-12 col-md-5">
            <div className="white-card rounded-lg profile-exp-icon p-4 mb-4">
              <LawyerImage />
            </div>
            <div className="white-card rounded-lg profile-information p-4 mb-4">
              <p className="f-18 semi-bold border-btm py-2">Personal</p>
              <div className="info-flex">
                <p className="f-14 d-flex justify-content-between"><span className="semi-bold">Address:  </span><span>United States</span></p>
                <p className="f-14 d-flex justify-content-between"><span className="semi-bold">Gender:  </span><span>Male</span></p>
                <p className="f-14 d-flex justify-content-between"><span className="semi-bold">Languages Spoken:  </span><span>English,French</span></p>
                <p className="f-14 d-flex justify-content-between"><span className="semi-bold">Legal Lawyerise:  </span><span>family(Divorce)  </span></p>
              </div>
            </div>
            <div className="white-card rounded-lg profile-about p-4 mb-4">
              <p className="f-18 semi-bold border-btm py-2">About Me</p>
              <label className="d-block mb-2 f-14 semi-bold">Description</label>
              <textarea className="form-control" placeholder="Description"></textarea>
            </div>
          </div>
          <div className="col-12 col-md-7">
            <div className="white-card rounded-lg profile-exp-docs p-4">
              <p className="f-18 semi-bold border-btm p-2">Experience</p>
              <LawyerProfile />
            </div>
          </div>
        </div> */}
      </div>
    </div>
  );
}
