import React, { useState, useEffect } from "react";
import { Metadata } from "next";
import "../../client/client.css";
import { Button } from "@/components/Form/Button";

export const metadata: Metadata = {
  title: "Payment Method",
  description: "Generated by create next app",
};

export default function PaymentMethod() {
  return (
    <div className="main-content expert-cases payment-methods">
      <div className="top-br">
        <h2 className="f-24">Payment</h2>
      </div>
      <div className="row ">
        <div className="col-12 col-md-8 mt-4">
          <div className="white-card rounded-lg p-4"></div>
        </div>
        <div className="col-12 col-md-8 mt-4">
          <div className="white-card rounded-lg p-4"></div>
        </div>
      </div>
    </div>
  );
}
