import React from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import { Button } from "@mui/material";
import "../../client/client.css";
import CaseCategory from "./_caseComponenets/CaseCategory";

export const metadata: Metadata = {
  title: "Case Categories",
  description: "Generated by create next app",
};

export default async function CaseCategories() {
  return (
    <ContentWrapper>
      <div className="top-title mb-4 mt-4">
        <h2 className="f-24">Choose the domain and module of your choice</h2>
      </div>
      <div className="select-case">
        <CaseCategory />
      </div>
    </ContentWrapper>
  );
}
