import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import TableAssign from "./_TableAssign";

export const metadata: Metadata = {
  title: "Pre Litigation Lawyers List",
  description: "Generated by create next app",
};

export default function AssignPreLitigationLawyer() {

  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Pre Litigation Lawyers List</h2>
      </div>
      <TableAssign />
   </div>
  );
}
