import React from "react";
import RequestTable from "./_RequestTable";
import { Metadata } from "next";
import "../../client/client.css";

export const metadata: Metadata = {
  title: "Case Requests",
  description: "Generated by create next app",
};

export default function TasksList() {
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Case Requests</h2>
      </div>
      <div className="res-table-box">
        <div className="mt-4">
          <RequestTable />
        </div>
      </div>
    </div>
  );
}
