import React, { useEffect, useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import db from "@/utils/connectDB";
import ClaimFinancialModel from "@/models/claim_financial.model";
import Case from "@/models/case.model";
import { Cases } from "@/types/Cases";
import FinancialReport from "@/app/container/lawyer-financial-report/page";

export const metadata: Metadata = {
  title: "Financial Report",
  description: "Generated by create next app",
};

export default async function FinancialReportView({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  let id: string | string[] | undefined | number = searchParams?.id;

  const fetchData = async (): Promise<any> => {
    await db.connectDB();

    const userData = await ClaimFinancialModel.findOne({ case_id: id })
      .limit(1)
      .lean();
    const caseData: Cases | null = await Case.findById(id).lean();

    return {
      data: {
        ...userData,
        lawyerFinancialReport: caseData?.lawyerFinancialReport,
      },
    };
  };

  const data: any = await fetchData();

  return (
    <div className="main-content expert-cases case-updates">
      <FinancialReport report={data} role={"expert"} />
    </div>
  );
}
