import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { Metadata } from "next";
import AnimateAuth from "@/components/Animate/AnimateAuth";
import Image from "next/image";
import "../../login/login.css";
import SignupComponent from "./_signup";
import logo from "@/assets/logo.png";
import female from "@/assets/female.png";
import loginbg from "@/assets/loginbg.png";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Lawyer Login",
  description: "Generated by create next app",
};

export default function LawyerSignup() {
  return (
    <AnimateAuth>
      <section className="login-section">
        <div className="row login-main-r align-items-center">
          <div className="col-12 col-md-12 col-lg-6 relative">
            <div
              className="login-img  login-background  text-white relative "
              style={{
                backgroundImage: `url(${loginbg.src})`,
              }}
            >
              <Image src={logo} className="login-logo" alt="logo" />
              <h2 className="f-52 semi-bold pt-4">
                Empowering <br></br> Legal Solutions
              </h2>
              <p className="f-15">Join Our Tech-Driven Platform Today </p>
            </div>
            <div className="login-abs-icon">
              <Image src={female} className="female" alt="logo" />
            </div>
          </div>
          <div className="col-6 col-md-6 col-lg-6">
            <div className="login-form pt-4 pb-3 px-5">
              <Card elevation={5} style={{ boxShadow: "none" }}>
                <CardContent className="p-0">
                <div className="login-title d-flex justify-content-between align-items-center pb-4">
                <h2 className="bold f-52"> Register your Account</h2>
                <div className="text-end">
                  <h5 className="f-14 mb-0">Have an account </h5>
                  <Link href="/auth/lawyer/login" className="bold dark f-14">
                    Login
                  </Link>
                </div>
              </div>
                  <SignupComponent />
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>
    </AnimateAuth>
  );
}
