
import React, { useState, useEffect } from "react";
import { Metadata } from "next";
import "../../client/client.css";
import Questionnaire from "@/app/container/questionnaire/page";

export const metadata: Metadata = {
  title: "Questionnaire list",
  description: "Generated by create next app",
};

export default function PreLitigationCaseOverview() {
  return (
    <div className="main-content expert-cases details-litigation">
      <div className="pre-case-overview row ">
        <div className="col-12 col-md-12 mt-4">
          <div className="white-card rounded-lg p-4">
            <div className="row ">
              <div className="col-12 ">
                <Questionnaire />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
