import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { Metadata } from "next";
import AnimateAuth from "@/components/Animate/AnimateAuth";
import VerifyToken from "./_verifyToken";

export const metadata: Metadata = {
  title: "Verify Token",
  description: "Generated by create next app",
};

export default function Verify() {
  return (
    <AnimateAuth>
      <section className="login-section">
        <div className="row login-main-r align-items-center">
          <div className="col-12">
            <div className="login-form  p-5">
              <Card elevation={5} style={{ boxShadow: "none" }}>
                <CardContent className="p-0">
                  <VerifyToken />
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>
    </AnimateAuth>
  );
}
