import React from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Button } from "@/components/Form/Button";
import { LawyerFilters } from "./_LawyerComponents/LawyerFilters";
import LawyerTable from "./_LawyerComponents/LawyerTable";

export const metadata: Metadata = {
  title: "Litigation Lawyers",
  description: "Generated by create next app",
};

export default function PreLitigationLawyers() {
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Pre-Litigation Lawyers</h2>
        <Button variant="contained" size="lg" className="expert-btn f-15">View Pre Litigation Lawyers</Button>
      </div>
     <LawyerFilters />
      <div className="res-table-box expert-lawyer">
        <div className="mt-4">
          <LawyerTable />
        </div>
      </div>
    </div>
  );
}
