"use client";

import React, { useState } from "react";
import { Metadata } from "next";
import "../../../client/client.css";
import LoadingButton from "@mui/lab/LoadingButton";
import MembersTable from "@/app/container/case-members/MemberTable";
import { useRouter } from "next/navigation";
import ContentWrapper from "@/components/Layout/Client/ContentWrapper";

// export const metadata: Metadata = {
//   title: "Case Members",
//   description: "Generated by create next app",
// };

export default function CaseMembersList({
  params,
}: {
  params: { id: string };
}) {
  const router = useRouter();
  const id = params.id;
  return (
    <ContentWrapper>
      <div className="main-content expert-cases case-members">
        <div className="top-br d-flex justify-content-between align-items-center">
          <h2 className="f-24 pb-3">Case Members</h2>

          {/* <LoadingButton
            variant="contained"
            className="client-btn f-14 rounded-lg"
            size="large"
            onClick={() => {
              router.push(`/client/case-members/add/${id}`);
            }}
          >
            <span>Add Member </span>
          </LoadingButton> */}
        </div>
        <MembersTable caseId={id} />
      </div>
    </ContentWrapper>
  );
}
