import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import LegalDocTable from "./_LegalDocComponent/LegalDocTable";

export const metadata: Metadata = {
  title: "Legal Document",
  description: "Generated by create next app",
};

export default function LegalDocument() {
  return (
    <div className="main-content expert-cases case-members">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Legal Document</h2>
      </div>
      <div className="res-table-box">
        <div className="mt-4">
          <LegalDocTable  />
        </div>
      </div>
    </div>
  );
}
