import React from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import place from "@/assets/placeholder.png";
import Image from "next/image";
import { Button } from "@/components/Form/Button";

export const metadata: Metadata = {
  title: "View PreLitigation Lawyer",
  description: "Generated by create next app",
};

export default function ViewPreLitigationLawyer() {
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">PreLitigation Lawyer Information</h2>
      </div>  
      <div className="liti-lawyers-list">
        <div className="row">
          <div className="col-12 col-md-6 mb-4">
            <div className="white-card litigate-lawyer p-4">
              <div className="row w-100 m-auto">
                <div className="col-12 col-md-4 col-lg-3">
                    <Image src={place} className="lawyers-icon-case" alt="" />
                </div>
                <div className="col-12 col-md-8 col-lg-9">
                    <div className="bggray litigation-lawyer-box rounded p-4">
                        <div className="liti-lawyer-flex d-flex justify-content-between ">
                            <span className="f-14  semi-bold">Lawyer Id:</span>
                            <span className="f-14">#2544664412</span>
                        </div>
                        <div className="liti-lawyer-flex d-flex justify-content-between ">
                            <span className="f-14 semi-bold">Full Name:</span>
                            <span className="f-14">Alec M. Thompson</span>
                        </div>
                        <div className="liti-lawyer-flex d-flex justify-content-between ">
                            <span className="f-14  semi-bold">Legal Expertise:</span>
                            <span className="f-14">Family(Divorce)  </span>
                        </div>
                        <div className="liti-lawyer-flex d-flex justify-content-between ">
                            <span className="f-14  semi-bold"> Expertise:</span>
                            <span className="f-14">5 years </span>
                        </div>
                    </div>
                    <div className="lawyer-btns mt-4 d-flex gap-3 align-items-center">
                        <Button variant="contained" className="expert-btn"> Assign</Button>
                        <Button variant="outline" className="expert-line-btn"> View More</Button>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
