import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import { Metadata } from "next";
import Link from "next/link";
import AnimateAuth from "@/components/Animate/AnimateAuth";
import LoginComponent from "../../login/_login";
import Image from "next/image";
import logo from "@/assets/logo.png";
import female from "@/assets/female.png";
import loginbg from "@/assets/loginbg.png";
import "../../login/login.css";

export const metadata: Metadata = {
  title: "Lawyer Login",
  description: "Generated by create next app",
};

export default function LawyerLogin() {
  return (
    <AnimateAuth>
      <section className="login-section">
        <div className="row login-main-r align-items-center">
          <div className="col-12 col-md-12 col-lg-6 relative">
            <div
              className="login-img  login-background  text-white relative "
              style={{
                backgroundImage: `url(${loginbg.src})`,
              }}
            >
              <Image src={logo} className="login-logo" alt="logo" />
              <h2 className="f-52 semi-bold pt-4">
                Empowering <br></br> Legal Solutions
              </h2>
              <p className="f-15">Join Our Tech-Driven Platform Today </p>
            </div>
            <div className="login-abs-icon">
              <Image src={female} className="female" alt="logo" />
            </div>
          </div>
          <div className="col-12 col-md-6 col-lg-6">
            <div className="login-form pt-4 pb-3 px-5">
              <Card elevation={5} style={{ boxShadow: "none" }}>
                <CardContent className="p-0">
                  <div className="login-title d-flex justify-content-between align-items-center pb-4">
                    <h2 className="bold"> Lawyer Login</h2>
                    {/* <h2 className="bold f-52"> Login your Account</h2> */}
                    <div className="text-end">
                      <h5 className="f-14 mb-0">Don&apos;t have an account </h5>
                      <Link
                        href="/auth/lawyer/signup"
                        className="bold dark f-14"
                      >
                        Register
                      </Link>
                    </div>
                  </div>
                  <LoginComponent role="lawyer" />
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>
    </AnimateAuth>
  );
}
