import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Button } from "@/components/Form/Button";
import FinancialTable from "./_FinancialTable";

export const metadata: Metadata = {
  title: "Financial Proposal",
  description: "Generated by create next app",
};

export default function FinancialProposal() {
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Financial Proposal</h2>
      </div>
      <div className="white-card financial-proposal p-5 ">
        <FinancialTable />

        <h4 className="f-18 semi-bold pb-3 pt-5 px-2">Signatures</h4>
        <div className="row w-100 m-auto">
          <div className="col-12 col-md-4">
            <p className="f-15">Case Manager Signature</p>
            <div className="manager-sign"></div>
          </div>
          <div className="col-12 col-md-4">
            <p className="f-15">Platform Signature</p>
            <div className="manager-sign platfom"></div>
          </div>
          <div className="col-12 col-md-4">
            <p className="f-15">Lawyer Signature</p>
            <div className="manager-sign lawyer"></div>
          </div>
        </div>
        <div className="send-btn mt-4 px-2">
          <Button variant="contained" className="expert-btn" size="lg">
            Send
          </Button>
        </div>
      </div>
    </div>
  );
}
