import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";

export const metadata: Metadata = {
  title: "Questioner",
  description: "Generated by create next app",
};

export default function Questioner() {
  return (
    <div className="main-content expert-cases case-members">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Questioner</h2>
      </div>
      <div className="questioner-box-pg">
        <div className="mt-4 white-card p-3 rounded-radius">
          <div className="questioner-ques rounded-radius p-4" style={{backgroundColor: "#AAD6CC"}}>
                <h6 className="mb-0 f-18 semi-bol"> Q1 - Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
          </div>
          <p className="p-3 f-14 gray mb-0">Ans 1 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
        <div className="mt-4 white-card p-3 rounded-radius">
          <div className="questioner-ques rounded-radius p-4" style={{backgroundColor: "#FBA86F"}}>
                <h6 className="mb-0 f-18 semi-bol"> Q2 - Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
          </div>
          <p className="p-3 f-14 gray mb-0">Ans 2 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
        <div className="mt-4 white-card p-3 rounded-radius">
          <div className="questioner-ques rounded-radius p-4" style={{backgroundColor: "#AEC7FF"}}>
                <h6 className="mb-0 f-18 semi-bol"> Q3 - Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
          </div>
          <p className="p-3 f-14 gray mb-0">Ans 3 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
        <div className="mt-4 white-card p-3 rounded-radius">
          <div className="questioner-ques rounded-radius p-4" style={{backgroundColor: "#D9C378"}}>
                <h6 className="mb-0 f-18 semi-bol"> Q4 - Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
          </div>
          <p className="p-3 f-14 gray mb-0">Ans 4 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
      </div>
    </div>
  );
}
