"use client";

import React, { useEffect, useState } from "react";
import { Metadata } from "next";
import "../../client/client.css";
import { Button } from "@/components/Form/Button";
import { CaseDetails } from "./_litigationCaseComponents/CaseDetails";
import { MinorDetails } from "./_litigationCaseComponents/MinorDetails";
import { PersonInfo } from "./_litigationCaseComponents/PersonInfo";
import { CaseInfo } from "./_litigationCaseComponents/CaseInfo";
import { FinancingStatus } from "./_litigationCaseComponents/FinancingStatus";
import { DocTracking } from "./_litigationCaseComponents/DocTracking";
import { Query } from "./_litigationCaseComponents/Query";
import { DocRequest } from "./_litigationCaseComponents/DocRequest";
import { Link } from "@mui/material";
import { DocRequestTrack } from "./_litigationCaseComponents/DocRequestTrack";
import { useSearchParams, useRouter } from "next/navigation";
import axios from "axios";
import { Cases } from "@/types/Cases";
import LoadingButton from "@mui/lab/LoadingButton";
import { useSession } from "next-auth/react";
import moment from "moment";
import { upperFirst } from "lodash";

// export const metadata: Metadata = {
//   title: "Litigation Cases",
//   description: "Generated by create next app",
// };

export default function LitigationCaseDetails() {
  const { data } = useSession();

  const params = useSearchParams();
  const router = useRouter();
  const id = params?.get("caseId");
  const [loading, setLoading] = useState<boolean>(false);
  const [load, setLoad] = useState<boolean>(false);

  const [caseData, setCaseData] = useState<Cases>();
  useEffect(() => {
    const getCaseById = async () => {
      try {
        setLoading(true);
        if (id) {
          const { data } = await axios.get(
            `/api/client/case/get-case?caseId=${id}`
          );
          setCaseData(data?.data);
        }

        setLoading(false);
      } catch (error) {
        console.log("err", error);
        setLoading(false);
      }
    };
    getCaseById();
  }, [id]);

  return (
    <div className="main-content expert-cases details-litigation">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Litigation Case Details</h2>
        <LoadingButton
          loading={load}
          variant="contained"
          className="client-btn f-14 rounded-lg"
          size="large"
          onClick={() => {
            setLoad(true);
            router.push("/client/litigation-cases");
          }}
        >
          <span>Go Back</span>
        </LoadingButton>
      </div>
      <div className="cases-details-liti white-card rounded-lg mt-4 p-4">
        <h4 className="f-18 bold">Case Details</h4>
        <div className="cases-liti bggray rounded-lg d-flex flex-wrap p-3">
          <p className="mb-0 f-14 d-flex gap-4">
            <span>Case Id :</span>
            <span className="semi-bold"># {caseData?.referenceId}</span>
          </p>
          <p className="mb-0 f-14 d-flex gap-4">
            <span>Client Name :</span>
            <span className="semi-bold">{data?.user?.firstName}</span>
          </p>
          <p className="mb-0 f-14 d-flex gap-4">
            <span>Registered on :</span>
            <span className="semi-bold">
              {moment(caseData?.createdAt).format("Do MMMM YYYY")}
            </span>
          </p>
          <p className="mb-0 f-14 d-flex gap-4">
            <span>Case Status :</span>
            <span className="semi-bold">
              {caseData?.status == "notResolved"
                ? "Not Resolved"
                : upperFirst(caseData?.status)}
            </span>
          </p>
        </div>
      </div>
      <div className="liti-minor-boxs row">
        <div className="col-12 col-md-8 mt-4">
          <div className="row">
            <div className="col-12 col-md-6">
              <CaseDetails   data={caseData} />
            </div>
            <div className="col-12 col-md-6">
              <MinorDetails />
            </div>
          </div>
          <div className="row">
            <div className="col-12 col-md-12 mt-4">
              <FinancingStatus />
            </div>
            <div className="col-12 col-md-12 mt-4">
              <DocTracking />
            </div>
          </div>
        </div>
        <div className="col-12 col-md-4 mt-4">
          <PersonInfo />
          <div className="case-personal-info mt-4">
            <CaseInfo />
          </div>
        </div>
      </div>
      <div className="comm-tools mt-4">
        <h3 className="f-18 semi-bold">Communication Tools</h3>
        <Query />
      </div>
      <div className="comm-tools req-tracking mt-4">
        <h3 className="f-18 semi-bold">Document Request Tracking</h3>
        <div className="res-tabs pt-4">
          <div className="res-tabs-box d-flex gap-3 align-items-center mb-4">
            <ul className="nav nav-tabs" id="myTab" role="tablist">
              <li className="nav-item" role="presentation">
                <button
                  className="nav-link "
                  id="manager-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#manager"
                  type="button"
                  role="tab"
                  aria-controls="manager"
                  aria-selected="false"
                >
                  Case Manager
                </button>
              </li>
              <li className="nav-item" role="presentation">
                <button
                  className="nav-link active"
                  id="other-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#other"
                  type="button"
                  role="tab"
                  aria-controls="other"
                  aria-selected="true"
                >
                  On Behalf of other
                </button>
              </li>
            </ul>
          </div>
          <div className="tab-content" id="myTabContent">
            <div
              className="tab-pane fade "
              id="manager"
              role="tabpanel"
              aria-labelledby="manager-tab"
            >
              <div className="doc-requets">
                <div className="row">
                  <div className="col-12 col-md-6">
                    <DocRequest />
                  </div>
                  <div className="col-12 col-md-6">
                    <DocRequest />
                  </div>
                </div>
                <div className="row">
                  <div className="col-12 col-md-6 mt-4">
                    <div className="doc-flex d-flex justify-content-between align-items-center">
                      <h3 className="f-18 semi-bold mb-4">
                        Document Request Tracking
                      </h3>
                      <Link href="/" className="dark f-15">
                        View All
                      </Link>
                    </div>
                    <DocRequestTrack />
                  </div>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade show active"
              id="other"
              role="tabpanel"
              aria-labelledby="other-tab"
            >
              <div className="doc-requets">
                <div className="row">
                  <div className="col-12 col-md-6">
                    <DocRequest />
                  </div>
                  <div className="col-12 col-md-6">
                    <DocRequest />
                  </div>
                </div>
                <div className="row">
                  <div className="col-12 col-md-6 mt-4">
                    <div className="doc-flex d-flex justify-content-between align-items-center">
                      <h3 className="f-18 semi-bold mb-4">
                        Document Request Tracking
                      </h3>
                      <Link href="/" className="dark f-15">
                        View All
                      </Link>
                    </div>
                    <DocRequestTrack />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
