import { Metadata } from "next";
import React from "react";
import ProfileComp from "./_profile";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function Profile() {
  return (
    <div className="container">
      <div className="row">
        <div className="col-8 mx-auto my-5">
          <div className="card">
            <div className="card-header">User profile</div>
            <div className="card-content p-4">
              <ProfileComp />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
