"use client";

// import { Metadata } from "next";
import React, { useEffect, useState } from "react";
import "../../expert/expert.css";
import Image from "next/image";
import send from "@/assets/assign.png";
import line from "@/assets/line.png";
import complete from "@/assets/complete.png";
import pending from "@/assets/pending.png";
import loan from "@/assets/loan.png";
import litigate from "@/assets/litigate.png";
import loc from "@/assets/loc.png";
import arrow from "@/assets/arrow-lg.png";
import { TodaysAppointments } from "./_dashboardComponents/TodaysAppointments";
import { CasesTable } from "./_dashboardComponents/CasesTable";
import { Query } from "./_dashboardComponents/Query";
import { StatusType } from "./_charts/StatusType";
import { Button } from "@/components/Form/Button";
import { LitigationChart } from "./_charts/LitigationChart";
import { PreLitigationChart } from "./_charts/PreLitigationChart";
import { LitigateChart } from "./_charts/LitigateChart";
import { ImportantDates } from "./_dashboardComponents/ImportantDates";
import { RecentNotifications } from "./_dashboardComponents/RecentNotifications";
import { ClientChart } from "./_charts/ClientChart";
import { LawyerChart } from "./_charts/LawyerChart";
import { ReportCard } from "./_dashboardComponents/ReportCard";
import { AskedDocs } from "./_dashboardComponents/AskedDocs";
import { axios } from "@/utils/axios";
import { DashboardData } from "@/types/Dashboard";
import { upperFirst } from "lodash";
import { useRouter } from "next/navigation";
import { useNotifications } from "@/queries/notifications";
import { useCases } from "@/queries/cases";
import Cards from "./_dashboardComponents/Cards";
import { CircularProgress, Link } from "@mui/material";

// export const metadata: Metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };

export default function Dashboard() {
  const router = useRouter();
  const [data, setData] = useState<DashboardData>();
  const [loading, setLoading] = useState<boolean>(false);

  const { data: NotificationData, isLoading, refetch } = useNotifications();

  const [page, setPage] = useState(1);
  const {
    data: caseData,
    isLoading: caseLoading,
    isFetching,
    refetch: caseRefetch,
  } = useCases({
    page,
    role: "lawyer",
    dataPerPage: 3,
  });

  const getDashboardData = () => {
    axios
      .get(`/api/lawyer/dashboard`)
      .then((res: any) => {
        setData(res);
      })
      .catch((error) => {
        console.error("Error fetching data:", error);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    caseRefetch();
  }, [page]);

  useEffect(() => {
    setLoading(true);
    getDashboardData();
  }, []);

  return (
    <div className="main-content expert-dashboard">
      {isLoading || loading ? (
        <p className="d-flex justify-content-center mt-5">
          <CircularProgress />
        </p>
      ) : (
        <>
          <Cards data={data} />

          {/* <!--- dahsboard main row  ----------> */}
          <div className="row dashboard-main-rw">
            <div className="col-12 col-md-7 col-lg-12">
              {/* <!--- Cases table ----------> */}
              <div className="white-card table-card rounded-lg p-4">
                <div className="table-responsive">
                  <CasesTable
                    data={caseData}
                    setPage={setPage}
                    caseLoading={caseLoading}
                  />
                </div>
              </div>
            </div>
            {/* <div className="col-12 col-md-5 col-lg-3">
              //  Today's Appointment 
              <div className="today-appnt">
                <TodaysAppointments />
              </div>
            </div> */}
          </div>

          {/* Query boxes */}
          {/* <Query /> */}

          {/* Active Claims */}
          <div className="row  my-4">
            <div className="col-12 col-md-7">
              <div className="cases-chart white-card rounded-lg">
                <div className="chart-top border-btm p-3">
                  <p className="f-18 semi-bold mb-0">Cases status by type</p>
                </div>
                <div className="p-3">
                  <StatusType data={data} />
                </div>
              </div>
            </div>
            <div className="col-12 col-md-5">
              <div className="active-claims white-card rounded-lg p-3">
                <p className="f-18 semi-bold">Active Claim</p>
                <div className="d-flex active-claim-list">
                  <span className="claim-status">Case ID</span>
                  <span className="claim-coln">:</span>
                  <span className="claim-status-cnt">
                    #{data?.activeCase?.referenceId}
                  </span>
                </div>
                <div className="d-flex active-claim-list">
                  <span className="claim-status">Case Category</span>
                  <span className="claim-coln">:</span>
                  <span className="claim-status-cnt">
                    {data?.activeCase?.category ?? "NA"}
                  </span>
                </div>
                <div className="d-flex active-claim-list">
                  <span className="claim-status">Status</span>
                  <span className="claim-coln">:</span>
                  <span className="claim-status-cnt">
                    {upperFirst(data?.activeCase?.status)}
                  </span>
                </div>
                <div className="d-flex active-claim-list">
                  <span className="claim-status">Client Name</span>
                  <span className="claim-coln">:</span>
                  <span className="claim-status-cnt">
                    {upperFirst(
                      data?.activeCase?.user?.firstName +
                        " " +
                        data?.activeCase?.user?.lastName
                    ) ?? "NA"}
                  </span>
                </div>
                <div className="claim-links d-flex gap-3 align-items-center  justify-content-center pt-4">
                  <a
                    onClick={() =>
                      router.push(
                        `/lawyer/case-documents/${data?.activeCase?._id}`
                      )
                    }
                    className="w-50 text-center cursor"
                  >
                    Documents Uploaded
                    <Image src={arrow} className="arrow-larg ms-3" alt="" />
                  </a>
                  {/* <Link href="#" className="w-50 text-center">
                    Claim Members
                    <Image src={arrow} className="arrow-larg ms-3" alt="" />
                  </Link> */}
                </div>
              </div>
            </div>
          </div>

          {/* Lawyers Assigned */}
          <div className="row mt-4">
            <div className="col-12 col-md-6">
              <div className="cases-chart white-card rounded-lg">
                <div className="px-3 py-4">
                  <p className="f-18 semi-bold">Case Assigned</p>
                  <div className="litigate-wrap d-flex gap-3">
                    <div
                      className="litigation-box rounded-lg p-4"
                      style={{ background: "#E3F5FF" }}
                    >
                      <div className="litigation-cnt d-flex align-items-center justify-content-between">
                        <div className="liti-left">
                          <p className="f-14">litigation</p>
                          <h3 className="f-24 bold">
                            {data?.litigationLawyer}
                          </h3>
                        </div>
                        <div className="liti-rght">
                          <Image src={complete} className="liti-icon" alt="" />
                        </div>
                      </div>
                      {/* <h5 className="f-13 mb-0">
                        <span className="green f-13 semi-bold me-2">
                          <Image alt="line" className="line-icon" src={line} />{" "}
                          8.5%
                        </span>
                        up from yesterday
                      </h5> */}
                      <div className="text-end pt-2">
                        <Button
                          className="expert-btn rounded-full"
                          size="sm"
                          onClick={() =>
                            router.push(`/lawyer/cases-list?type=litigation`)
                          }
                        >
                          View
                        </Button>
                      </div>
                    </div>
                    <div
                      className="litigation-box rounded-lg p-4"
                      style={{ background: "#E5ECF6" }}
                    >
                      <div className="litigation-cnt d-flex align-items-center justify-content-between">
                        <div className="liti-left">
                          <p className="f-14">Pre-litigation</p>
                          <h3 className="f-24 bold">
                            {data?.preLitigationLawyer}
                          </h3>
                        </div>
                        <div className="liti-rght">
                          <Image src={complete} className="liti-icon" alt="" />
                        </div>
                      </div>
                      {/* <h5 className="f-13 mb-0">
                        <span className="green f-13 semi-bold me-2">
                          <Image alt="line" className="line-icon" src={line} />{" "}
                          8.5%
                        </span>
                        up from yesterday
                      </h5> */}
                      <div className="text-end pt-2">
                        <Button
                          className="expert-btn rounded-full"
                          size="sm"
                          onClick={() =>
                            router.push(`/lawyer/cases-list?type=preLitigation`)
                          }
                        >
                          View
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-12 col-md-3">
              <div className="litigate-succes white-card rounded-lg p-3">
                <p className="f-18 semi-bold">litigation</p>
                <LitigationChart data={data} />
              </div>
            </div>
            <div className="col-12 col-md-3">
              <div className="litigate-succes white-card rounded-lg p-3">
                <p className="f-18 semi-bold">Pre-litigation</p>
                <PreLitigationChart data={data} />
              </div>
            </div>
          </div>

          {/* Litigation prelitigation*/}
          {/* <div className="row mt-4">
            <div className="col-12 col-md-8">
              <div className="litig-chart white-card rounded-lg p-3">
                <LitigateChart />
              </div>
            </div>
            <div className="col-12 col-md-4">
              <div className="litig-succes-case white-card rounded-lg w-100 p-4 mb-3">
                <div
                  className="query-box w-100  rounded-lg"
                  style={{ backgroundColor: "#FFEFE8" }}
                >
                  <p className="f-18 mb-2 gray">
                    <Image className="send-icon" src={send} alt="send" /> Assign
                    Lawyer to{" "}
                  </p>
                  <h3 className="bold f-24 mb-0">
                    Prelitigation Case{" "}
                    <Image className="arrow-lg" src={arrow} alt="arrow" />
                  </h3>
                </div>
              </div>
              <div className="litig-succes-case white-card rounded-lg w-100 p-4">
                <div
                  className="query-box w-100  rounded-lg"
                  style={{ backgroundColor: "#FFEFE8" }}
                >
                  <p className="f-18 mb-2 gray">
                    <Image className="send-icon" src={send} alt="send" /> Assign
                    Lawyer to{" "}
                  </p>
                  <h3 className="bold f-24 mb-0">
                    Prelitigation Case{" "}
                    <Image className="arrow-lg" src={arrow} alt="arrow" />
                  </h3>
                </div>
              </div>
            </div>
          </div> */}

          {/* Important dates */}
          <div className="row">
            <div className="col-12 col-md-6  mt-4">
              <ImportantDates  data={data?.courtHearing}/>
            </div>
            {/* <div className="col-12 col-md-3  mt-4">
              <div className="litig-succes-case white-card rounded-lg w-100 p-4 mb-3">
                <div
                  className="query-box w-100  rounded-lg"
                  style={{ backgroundColor: "#B9E9EE" }}
                >
                  <p className="f-18 mb-2 semi-bold">
                    <Image
                      className="send-icon me-2"
                      src={loc}
                      alt="location"
                    />
                    Edit Request
                  </p>
                  <h3 className="bold f-24 mb-0">10 Document </h3>
                </div>
              </div>
              <div className="litig-succes-case white-card rounded-lg w-100 p-4">
                <div
                  className="query-box w-100  rounded-lg"
                  style={{ backgroundColor: "#B9E9EE" }}
                >
                  <p className="f-18 mb-2 semi-bold">
                    <Image
                      className="send-icon me-2"
                      src={loc}
                      alt="location"
                    />
                    Total Requested
                  </p>
                  <h3 className="bold f-24 mb-0">10 Document </h3>
                </div>
              </div>
            </div> */}
            <div className="col-12 col-md-6 mt-4">
              <RecentNotifications data={NotificationData?.data}/>
            </div>
          </div>

          {/* Litigation charts */}
          {/* <div className="row">
            <div className="col-12 col-md-6  mt-4">
              <div className=" white-card rounded-lg  p-4">
                <h3 className="f-20 semi-bold pb-3">Litigation</h3>
                <div className="row">
                  <div className="col-12 col-md-6">
                    <div className="bg-white p-4 shadow-card">
                      <h3 className="f-20 semi-bold">Client</h3>
                      <ClientChart />
                    </div>
                  </div>
                  <div className="col-12 col-md-6">
                    <div className="bg-white p-4 shadow-card">
                      <h3 className="f-20 semi-bold">Lawyer</h3>
                      <ClientChart />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-12 col-md-6  mt-4">
              <div className=" white-card rounded-lg  p-4">
                <h3 className="f-20 semi-bold pb-3">Pre-Litigation</h3>
                <div className="row">
                  <div className="col-12 col-md-6">
                    <div className="bg-white p-4 shadow-card">
                      <h3 className="f-20 semi-bold">Client</h3>
                      <LawyerChart />
                    </div>
                  </div>
                  <div className="col-12 col-md-6">
                    <div className="bg-white p-4 shadow-card">
                      <h3 className="f-20 semi-bold">Lawyer</h3>
                      <LawyerChart />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div> */}

          {/* Submitted Evaluation report */}
          <div className="row">
            <div className="col-12 col-md-6  mt-4">
              <div className=" white-card rounded-lg report-card  p-4">
                <h3 className="f-20 semi-bold pb-3">
                  Submitted Financial Report
                </h3>
                <ReportCard data={data?.evalReports} />
              </div>
            </div>
            <div className="col-12 col-md-6  mt-4">
              <div className=" white-card rounded-lg report-card  p-4">
                <h3 className="f-20 semi-bold pb-3">Asked Documents</h3>
                <AskedDocs data={data?.documents}/>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
