import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import AssignLawyer from "./_AssignLawyer";

export const metadata: Metadata = {
  title: "Assign Litigation Lawyers",
  description: "Generated by create next app",
};

export default function AssignLitigationLawyer() {
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Litigation Lawyers List</h2>
      </div>
      <AssignLawyer />
    </div>
  );
}
