"use client";
import React, { useEffect, useState } from "react";
import "../../client/client.css";
import Image from "next/image";
import loan from "@/assets/loan.png";

import about from "@/assets/about.png";
import line from "@/assets/line.png";
import complete from "@/assets/complete.png";
import pending from "@/assets/pending.png";
import swap from "@/assets/swap.png";
import litigate from "@/assets/litigate.png";
import {
  Button,
  CircularProgress,
  LinearProgress,
  linearProgressClasses,
  Link,
} from "@mui/material";
// import { CasesChart } from "./_charts/CasesChart";
import { Query } from "./_dashboardComponents/Query";
import { TodaysAppointments } from "./_dashboardComponents/TodaysAppointments";
import { StatusType } from "./_charts/StatusType";
import { ProgressCases } from "./_dashboardComponents/ProgressCases";
// import { RevenueChart } from "./_charts/RevenueChart";
// import { PriorityCase } from "./_charts/PriorityCase";
import { axios } from "@/utils/axios";
import { DashboardData } from "@/types/Dashboard";
import { upperFirst } from "lodash";
import { useRouter } from "next/navigation";
import { useNotifications } from "@/queries/notifications";
import { useCases } from "@/queries/cases";
import Cards from "./_dashboardComponents/Cards";
import { CasesTable } from "./_dashboardComponents/CasesTable";
// export const metadata: Metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };

export default function Dashboard() {
  const router = useRouter();
  const [data, setData] = useState<DashboardData>();
  const [loading, setLoading] = useState<boolean>(false);

  const { data: NotificationData, isLoading, refetch } = useNotifications();

  const [page, setPage] = useState(1);
  const {
    data: caseData,
    isLoading: caseLoading,
    isFetching,
    refetch: caseRefetch,
  } = useCases({
    page,
    role: "client",
    dataPerPage: 3,
  });

  const getDashboardData = () => {
    axios
      .get(`/api/client/dashboard`)
      .then((res: any) => {
        setData(res);
      })
      .catch((error) => {
        console.error("Error fetching data:", error);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    caseRefetch();
  }, [page]);

  useEffect(() => {
    setLoading(true);
    getDashboardData();
  }, []);

  return (
    <div className="main-content">
      {isLoading || loading ? (
        <p className="d-flex justify-content-center mt-5">
          <CircularProgress />
        </p>
      ) : (
        <>
          <Cards data={data} />
          {/* <!--- dahsboard main row  ----------> */}
          <div className="row dashboard-main-rw">
            <div className="col-12 col-md-7 col-lg-9">
              {/* <div className="cases-chart white-card p-4 rounded-lg">
                <div className="chart-top d-flex align-items-center justify-content-between">
                  <p className="f-18 semi-bold">No. of Cases</p>
                  <select className="chart-select">
                    <option>Jan</option>
                    <option>Feb</option>
                    <option>March</option>
                    <option>April</option>
                  </select>
                </div>
                <CasesChart />
              </div> */}
              {/* <div className="cases-query">
            <Query />
          </div> */}
              {/* <!--- Cases table ----------> */}
              <div className="white-card table-card rounded-lg p-4 my-4">
                <h4 className="f-20">Active Cases</h4>
                <div className="table-responsive mt-4">
                  <CasesTable
                    data={caseData}
                    setPage={setPage}
                    caseLoading={caseLoading}
                  />
                </div>
              </div>
            </div>
            <div className="col-12 col-md-5 col-lg-3">
              {/* Today's Appointment */}
              {/* <div className="today-appnt">
            <TodaysAppointments />
          </div> */}
              <div className="know-about bgdark text-white text-center rounded-lg">
                <h3 className="f-24 pb-3">Know more about the platform</h3>
                <Button
                  variant="contained"
                  className="white-btn bg-white rounded-lg dark"
                  onClick={() =>
                    router.push(`${process?.env?.NEXT_PUBLIC_AUTH_URL}`)
                  }
                >
                  View Glossary
                </Button>
                <Image
                  className="know-icon w-100 h-auto mt-4"
                  src={about}
                  alt=""
                />
              </div>
            </div>
          </div>

          {/* Cases types */}
          <div className="row cases-type ">
            <div className="col-12 col-md-7 mt-4">
              <div className="status-type">
                <div className="white-card rounded-lg">
                  <div className="status-title border-btm p-3">
                    <h3 className="f-18 semi-bold mb-0">
                      Cases status by type
                    </h3>
                  </div>
                  <div className="status-chart p-3">
                    <StatusType data={data} />
                  </div>
                </div>
              </div>
            </div>
            <div className="col-12 col-md-5 mt-4">
              <ProgressCases data={data} />
            </div>
          </div>

          {/* Active Cases */}
          <div className="row cases-type active-cs">
            <div className="col-12 col-md-7 col-lg-8 mt-4">
              <div className="status-type">
                {/* <div className="white-card rounded-lg mb-4">
                  <div className="status-title border-btm p-3">
                    <h3 className="f-18 semi-bold mb-0">Active Cases</h3>
                  </div>
                  <div className="status-chart p-3">
                    <ActiveCases />
                  </div>
                </div> */}
                {/* <div className="white-card rounded-lg">
                  <div className="status-title p-3">
                    <div className="d-flex align-items-center justify-content-between">
                      <p className="gray f-14 mb-2">Total Revenue</p>
                      <Link href="#">
                        <Image src={swap} className="swap-icon" alt="" />
                      </Link>
                    </div>

                    <h3 className="f-32 semi-bold">$190,090.36</h3>
                  </div>
                  <div className="status-chart p-3 mb-4">
                    <RevenueChart />
                  </div>
                </div> */}
              </div>
            </div>
            <div className="col-12 col-md-5 col-lg-4 mt-4">
              <div className="priority-cases">
                <div className="white-card rounded-lg">
                  {/* <div className="status-title p-3 border-btm">
                    <p className="f-18 semi-bold mb-0">Priority Cases</p>
                  </div> */}
                  {/* <div className="status-chart p-3 mb-4">
                    <div className="border-btm">
                      <PriorityCase />
                    </div>
                    <div className="cases-priorty">
                      <p className="f-18 mb-2 mt-4 semi-bold">Cases</p>
                      <div className="prior-cases f-16 d-flex align-items-center justify-content-between">
                        <span className="prior-doc">
                          Total Document Uploaded
                        </span>
                        <span className="prior-percent">27% </span>
                      </div>
                      <div className="prior-cases f-16 d-flex align-items-center justify-content-between">
                        <span className="prior-doc">Total Accepted Claim</span>
                        <span className="prior-percent">27%</span>
                      </div>
                      <div className="prior-cases f-16 d-flex align-items-center justify-content-between">
                        <span className="prior-doc">
                          Total Referral Clients{" "}
                        </span>
                        <span className="prior-percent">27% </span>
                      </div>
                      <div className="prior-cases f-16 d-flex align-items-center justify-content-between">
                        <span className="prior-doc">Total Rewards Earned </span>
                        <span className="prior-percent">27% </span>
                      </div>
                    </div>
                  </div> */}
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
