export const expiration = {
  JWT_SECRET: "thisisasamplesecret",
  JWT_ACCESS_EXPIRATION_MINUTES: 30,
  JWT_REFRESH_EXPIRATION_DAYS: 30,
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 12,
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10,
};
