"use client";

import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import Image from "next/image";
import { Button } from "@/components/Form/Button";
import doc from "@/assets/folder-open.png";
import { Link } from "@mui/material";

export const metadata: Metadata = {
  title: "Case Update",
  description: "Generated by create next app",
};

export default function UpdateCase() {
  const [referenceId, setReference] = useState<string>("");
  const [subVal, setDateVal] = useState<string>("");
  const [submissionDate, setSubmission] = useState<string>("");

  return (
    <div className="upate-doc-cnt">
      <div className="doc-filters-form mb-4">
        <div className="row mt-4">
          <div className="col-12 col-md-3">
            <div className="filter-input">
              <input
                type="text"
                className="form-control filter-ip"
                placeholder="Document Name"
              />
            </div>
          </div>
          <div className="col-12 col-md-2">
            <div className="filter-input">
              {/* <label className="date-label">Submission Date:</label> */}
              <input
                type="date"
                className="form-control filter-ip"
                placeholder="Submission Date"
                value={subVal}
                onChange={(e) => {
                  let date = e.target.value;
                  setDateVal(date);
                  const [year, month, day] = date.split("-");
                  // return `${day}/${month}/${year}`;
                  setSubmission(`${day}/${month}/${year}`);
                }}
              />
            </div>
          </div>
          <div className="col-12 col-md-2">
            <div className="filter-input">
              <input
                type="time"
                className="form-control filter-ip"
                placeholder="Time"
              />
            </div>
          </div>
          <div className="col-12 col-md-2">
            <div className="filter-input">
              <input
                type="text"
                className="form-control filter-ip"
                placeholder="Attendees Name"
              />
            </div>
          </div>
          <div className="col-12 col-md-3">
            <div className=" col-12 col-md-2 filter-btn">
              <Button variant="contained" size="sm" className="expert-btn">
                <span className="f-16">Search</span>
              </Button>
            </div>
          </div>
        </div>
      </div>
      {/* Important dates */}
      <div className="row">
        <div className="col-12 col-md-6">
          <div className="today-appoint import-dates white-card rounded-lg">
            <div
              className="appoint-title bggreen"
              style={{ borderRadius: "10px 10px 0 0" }}
            >
              <h3 className="f-18 semi-bold p-3 mb-0">Important Dates</h3>
            </div>

            <div className="active-claims-box p-3">
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case ID</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">ED2312</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Category</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Description</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  Lorem ipsum dolor sit amet consectetur adipiscing elit, sed
                  do.{" "}
                </span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Location</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Lorem ipsum </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Communication */}
      <div className="row mt-4">
        <div className="col-12 col-md-8">
          <div className="communication-div white-card p-4">
            <div className="comm-header d-flex justify-content-between align-items-center pb-2 border-btm">
              <p className="f-14 mb-0">
                <span className="semi-bold">Title of Communication:</span> Lorem
                Ipsum
              </p>
              <p className="f-14 mb-0">
                <span className="semi-bold">Date:</span> 12/02/2023
              </p>
            </div>
            <p className="semi-bold f-16 pt-4">Attendees</p>
            <div className="attendy-tags d-flex gap-2">
              <span style={{ backgroundColor: "#FC9DB2" }}>Lorem Ipsum</span>
              <span style={{ backgroundColor: "#FFD5C8" }}>Lorem Ipsum</span>
              <span style={{ backgroundColor: "#A3ACC9" }}>Lorem Ipsum</span>
              <span style={{ backgroundColor: "#F7C894" }}>Lorem Ipsum</span>
            </div>
            <p className="semi-bold f-16 pt-4 mb-2">Points discussed</p>
            <ul className="gray f-14">
              <li>Lorem ipsum dolor sit amet</li>
              <li>Lorem ipsum dolor sit amet</li>
              <li>Lorem ipsum dolor sit amet</li>
              <li>Lorem ipsum dolor sit amet</li>
            </ul>
            <p className="semi-bold f-16 pt-4 mb-2">
              Documents attached of Communication
            </p>
            <div className="row document-row">
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-upde">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-upde">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-upde">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
            </div>
            <p className="semi-bold f-16 pt-4 mb-2">
              Documents Exchanged
            </p>
            <div className="row document-row">
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-exchnage">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-exchnage">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
              <div className="col-12 col-md-4  col-lg-4 col-xl-3  mb-4">
                <Link href="/expert/pre-litigation-claim-document" className="text-decoration-none" >
                  <div className="folder-card rounded recent-folder case-exchnage">
                    <Image src={doc} className="doc-icn" alt="doc" />
                    <div className="doc-filter-fl">
                      <h5 className="f-16 mb-0">#3422_Category</h5>
                      <p className="f-13 mb-0 gray">50 MB</p>
                    </div>
                  </div>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
