import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Button } from "@/components/Form/Button";
import UpdateCase from "./_UpdateCase";

export const metadata: Metadata = {
  title: "Case Update",
  description: "Generated by create next app",
};

export default function CaseUpdate() {

  return (
    <div className="main-content expert-cases case-updates">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Case Update</h2>
      </div>
     <UpdateCase />
    </div>
  );
}
