import React from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import "../../expert/expert.css";
import LitigationLawyers from "@/app/container/litigation-lawyers/page";

export const metadata: Metadata = {
  title: "Litigation Lawyers",
  description: "Generated by create next app",
};

export default async function _LitigationLawyers() {
  return (
    <ContentWrapper>
      <div className="main-content">
        <LitigationLawyers role="expert" />
      </div>
    </ContentWrapper>
  );
}
