import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import { Metadata } from "next";
import Link from "next/link";
import AnimateAuth from "@/components/Animate/AnimateAuth";
import Image from "next/image";
import logo from "@/assets/login.png";
import { Button } from "@mui/material";
import AddUserComponent from "./_addUser";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function AddUser() {
  return (
    <AnimateAuth>
      <section className="login-section">
        <div className="row login-main-r align-items-center">
          <div className="col-12 ">
            <div className="login-form pt-4 pb-3 px-5">
              <h2 className="bold mb-3 pt-4">Add Expert</h2>
              <Card elevation={5} style={{ boxShadow: "none" }}>
                <CardContent className="p-0">
                  <AddUserComponent />
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>
    </AnimateAuth>
  );
}
