import { Metadata } from "next";
import React from "react";
import "../../client/client.css";
import Image from "next/image";
import doc from "@/assets/folder-open.png";
import { useEffect, useState } from "react";
import { Box, Button, Link } from "@mui/material";
import { ResFilters } from "./_resComponents/ResFilters";
import { ResTable } from "./_resComponents/ResTable";
import { SharedTable } from "./_resComponents/SharedTable";

export const metadata: Metadata = {
  title: "Documents",
  description: "Generated by create next app",
};

export default function RepresentativeIndivisual() {
  return (
    <div className="main-content client-docs">
      <div className="top-br d-flex align-items-center justify-content-between">
      <h2 className="f-24">Representative Individual</h2>
      <div className="d-flex gap-2">
        <Button variant="contained" className="reminder-btn">Send Reminder</Button>
        <Button variant="contained" className="stop-btn">Stop Reminder</Button>
      </div>
      </div>
      
      <ResFilters />
      <div className="res-tabs pt-4">
        <div className="res-tabs-box d-flex gap-3 align-items-center mb-4">
          <ul className="nav nav-tabs" id="myTab" role="tablist">
            <li className="nav-item" role="presentation">
              <button
                className="nav-link active"
                id="all-tab"
                data-bs-toggle="tab"
                data-bs-target="#all"
                type="button"
                role="tab"
                aria-controls="all"
                aria-selected="true"
              >
                All
              </button>
            </li>
            <li className="nav-item" role="presentation">
              <button
                className="nav-link"
                id="shared-tab"
                data-bs-toggle="tab"
                data-bs-target="#shared"
                type="button"
                role="tab"
                aria-controls="shared"
                aria-selected="false"
              >
                Shared
              </button>
            </li>
          </ul>
          <Button className="white-btn bg-white">Add New</Button>
        </div>
        <div className="tab-content" id="myTabContent">
          <div
            className="tab-pane fade show active"
            id="all"
            role="tabpanel"
            aria-labelledby="all-tab"
          >
            <div className="res-table-box">
              <div className="table-responsive mt-4">
                <ResTable />
              </div>
            </div>
          </div>
          <div
            className="tab-pane fade"
            id="shared"
            role="tabpanel"
            aria-labelledby="shared-tab"
          >
            <div className="res-table-box border-table">
              <div className="table-responsive mt-4">
                <SharedTable />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
