import { PaginateData } from "@/types/Paginate";
import { User as UserType } from "@/types/User";
import db from "@/utils/connectDB";
import { Metadata } from "next";
import React from "react";
import "../../../client/client.css";
import TaskModel from "@/models/tasks.model";
import TaskUpdateForm from "@/app/container/UpdateTask";
import mongoose from "mongoose";

export const metadata: Metadata = {
  title: "Task Update",
  description: "Generated by create next app",
};

export default async function UpdateTask({
  searchParams,
}: {
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  let page: string | string[] | undefined | number = searchParams?.page;
  let id: string | string[] | undefined | number = searchParams?.id;
  let task_id: any = searchParams?.task_id;
  let isDocument: string | string[] | undefined | number =
    searchParams?.isDocument;
  let isUpdated: string | string[] | undefined | number =
    searchParams?.isUpdated;
  const objectID = new mongoose.Types.ObjectId(task_id);
  page = !!page ? +page : 1;
  const fetchData = async (
    pageNumber: number
  ): Promise<PaginateData<UserType>> => {
    await db.connectDB();
    const totalUsers = await TaskModel.countDocuments({});
    const totalPages = Math.ceil(totalUsers / 10);
    if (pageNumber > totalPages) {
      pageNumber = totalPages;
    }
    const start = pageNumber - 1;

    const userData = await TaskModel.findOne({ _id: objectID }).exec();
    return {
      data: userData,
      currentPage: pageNumber,
      totalEntries: totalUsers,
    };
  };

  const data = await fetchData(page);

  console.log(data?.data, "datadatadata");

  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Update Task</h2>
      </div>
      <div className="white-card p-4 mt-4 indivi-form rounded">
        <div className="mb-4">
          <TaskUpdateForm
            case_id={id}
            data={data}
            task_id={task_id}
            role={"client"}
            isUpdated={isUpdated}
            isDocument={isDocument}
          />
        </div>
      </div>
    </div>
  );
}
