import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Button, Link } from "@mui/material";
import star from "@/assets/star.png";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Client Feedback",
  description: "Generated by create next app",
};

export default function Reminders() {
  return (
    <div className="main-content expert-cases case-members request-doc-upload">
      <div className="top-br">
        <h2 className="f-24">Client Feedback</h2>
      </div>
      <div className="row">
        <div className="col-12 col-md-6 mt-4">
          <div className="today-appoint import-dates white-card rounded-lg client-feedback">
            <div className="active-claims-box p-3">
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case ID</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">ED2312</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Type</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Client Name</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Jorge</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Category</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Claim Closed</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Lawyer Assigned</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Joseph</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Duration</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">3 months</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Ratings</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <Image src={star} className="rating-str" alt="" />
                  <Image src={star} className="rating-str" alt="" />
                  <Image src={star} className="rating-str" alt="" />
                </span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Feedback</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <Link href="/" className="feedback-link dark">
                    View
                  </Link>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="col-12 col-md-6 mt-4">
          <div className="today-appoint import-dates white-card rounded-lg client-feedback">
            <div className="active-claims-box p-3">
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case ID</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">ED2312</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Type</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Client Name</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Jorge</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Category</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Claim Closed</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Lawyer Assigned</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Joseph</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Duration</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">3 months</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Ratings</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <Image src={star} className="rating-str" alt="" />
                  <Image src={star} className="rating-str" alt="" />
                  <Image src={star} className="rating-str" alt="" />
                </span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Feedback</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <Link href="/" className="feedback-link dark">
                    View
                  </Link>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
