"use client";
import { Metadata } from "next";
import React, { useState } from "react";
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
import "../../../admin/admin.css";
import { z } from "zod";
import { useHookForm } from "@/hooks/useHookForm";
import { InputField } from "@/components/Form/InputField";
import LoadingButton from "@mui/lab/LoadingButton";
import Form from "@/components/Form/Form";

type FormValues = {
  title: string;
  description: string;
};

const schema = z.object({
  title: z.string({ required_error: "ddfds" }).min(1, "Title is required"),
  deacription: z.string().min(1, "Description is required"),
});

export const metadata: Metadata = {
  title: "Terms",
  description: "Generated by create next app",
};

export default function TermsForm() {
  const [value, setValue] = useState("");

  const { methods, setValues } = useHookForm<FormValues, typeof schema>(schema);
  const { formState, control, reset } = methods;
  const [loading, setLoading] = useState(false);
  return (
    <div className="privacy-forms indivi-form">
      <Form<FormValues>
        onSubmit={async (values) => {
          alert("Abc");
        }}
        methods={methods}
      >
        <div className="row mt-3">
          <div className="col-12 col-md-12 mt-3">
            <InputField
              error={formState.errors["title"]}
              label="Title"
              name="title"
              className="bglight-ip"
              control={control}
            />
          </div>
          <div className="col-12 mt-3">
            <ReactQuill theme="snow" value={value} onChange={setValue} />
          </div>
          <div className="col-12 col-md-6 mt-4 text-right">
            <LoadingButton
              loading={loading}
              variant="contained"
              type="submit"
              className="load-btn"
              size="large"
            >
              <span>Submit</span>
            </LoadingButton>
          </div>
        </div>
      </Form>
    </div>
  );
}
