import React from "react";
import "../../client/client.css";
import { Metadata } from "next";
import Attorney from "./Attorney";

export const metadata: Metadata = {
  title: "Client/Attorney",
  description: "Generated by create next app",
};

export default function AttorneyPage() {
  return <Attorney />;
}
