import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import down from "@/assets/down.png";
import Image from "next/image";
import { Button } from "@/components/Form/Button";
import { Link } from "@mui/material";
import { HearingDetails } from "./_courtComponents/HearingDetails";
import { Conclusions } from "./_courtComponents/Conclusions";
import { Reminder } from "./_courtComponents/Reminder";

export const metadata: Metadata = {
  title: "Court Hearing",
  description: "Generated by create next app",
};

export default function PastCourtHearingDetails() {
  return (
    <div className="main-content expert-cases case-updates court-hearing">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24 pb-3">Court Hearing</h2>
      </div>
      <div className="row">
        <div className="col-12 col-md-6 col-lg-7">
          <div className="white-card p-4 hearings-past mb-4">
            <HearingDetails />
          </div>
          <h4 className="f-18 semi-bold pb-3">
            Conclusion Of the Court Hearing:
          </h4>
          <div className="white-card p-4 hearings-past mb-4">
            <Conclusions />
          </div>
        </div>
        <div className="col-12 col-md-6 col-lg-5">
        <div className="hearings-reminder mb-4">
            <Reminder />
          </div>
        </div>
      </div>
    </div>
  );
}
