"use client";

import React, { useEffect, useState } from "react";
import ContentWrapper from "@/components/Layout/Admin/ContentWrapper";
import { Metadata } from "next";
import "../../client/client.css";
import Box from "@mui/material/Box";
import PrivacyPolicy from "./privacy-policy/Privacy";
import LeaseContractDetails from "./_RequestJudicialForm/LeaseContractDetails";
import LeaseClauses from "./_RequestJudicialForm/LeaseClauses";
import PremisesCharacteristics from "./_RequestJudicialForm/PremisesCharacteristics";
import BuildingCharacteristics from "./_RequestJudicialForm/BuildingCharacteristics";
import LocalityInformation from "./_RequestJudicialForm/LocalityInformation";
import PremisesExpertise from "./_RequestJudicialForm/PremisesExpertise";
import RentAdjustment from "./_RequestJudicialForm/RentAdjustment";
import ThankuStep from "./thanku-page/page";
import { useSearchParams, useRouter } from "next/navigation";
import CircularProgress from "@mui/material/CircularProgress";
import axios from "axios";
import LinearProgress, {
  LinearProgressProps,
} from "@mui/material/LinearProgress";
import { Judicial } from "@/types/Judicial";
import Review from "./_RequestJudicialForm/Review";
import AddForm from "./_RequestJudicialForm/AddForm";

const steps = ["Lorem ipsum", "Lorem ipsum", "Lorem ipsum"];

// export const metadata: Metadata = {
//   title: "Eviction Assessment Form",
//   description: "Generated by create next app",
// };

export default function RequestJudicialDeterminationRent() {
  const router = useRouter();

  const [progress, setProgress] = useState(10);

  const [loading, setLoading] = useState(false);

  const [rentData, setRentData] = useState<Judicial>();

  const searchParmas = useSearchParams();
  const progressFromQuery = searchParmas?.get("progress");
  const caseFromQuery = searchParmas?.get("caseId");

  function LinearProgressWithLabel(
    props: LinearProgressProps & { value: number }
  ) {
    return (
      <Box sx={{ display: "flex", alignItems: "center" }}>
        <Box sx={{ width: "100%", mr: 1 }}>
          <LinearProgress variant="determinate" {...props} />
        </Box>
      </Box>
    );
  }

  useEffect(() => {
    if (progressFromQuery) {
      setProgress(+progressFromQuery);
    }
  }, [progressFromQuery]);

  useEffect(() => {
    const getCaseById = async () => {
      try {
        setLoading(true);
        if (caseFromQuery) {
          const { data } = await axios.get(
            `/api/client/category/judicial/getJudicial?caseId=${caseFromQuery}`
          );
          if (data?.data) {
            setProgress(data?.data?.progress);
            setRentData(data.data);
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", data?.data?.caseId);
            searchParmas.set("progress", data?.data?.progress);
            router.push(
              `/client/judicial-determination-of-rent?${searchParmas.toString()}`
            );
          } else {
            const searchParmas = new URLSearchParams();
            searchParmas.set("caseId", caseFromQuery);
            searchParmas.set("progress", "10");
            router.push(
              `/client/judicial-determination-of-rent?${searchParmas.toString()}`
            );
          }
        }
        setLoading(false);
      } catch (error) {
        console.log("err", error);
        setLoading(false);
      }
    };
    getCaseById();
  }, [caseFromQuery, progressFromQuery]);

  const handleNext = async () => {
    try {
      if (progress === 10) {
        setLoading(true);
        let id;
        let progress;
        if (rentData) {
          if (rentData.caseId === caseFromQuery) {
            const { data } = await axios.post(
              "/api/client/category/judicial/createJudicial",
              {
                caseId: caseFromQuery,
                progress: 20,
                nextProgress: 20,
              }
            );
            id = data.data.caseId;
            progress = data?.data?.progress;
          }
        } else {
          const { data } = await axios.post(
            "/api/client/category/judicial/createJudicial",
            {
              caseId: caseFromQuery,
              progress: 20,
              nextProgress: 20,
            }
          );
          id = data.data.caseId;
          progress = data?.data?.progress;
        }
        const searchParmas = new URLSearchParams();
        searchParmas.set("caseId", id);
        searchParmas.set("progress", progress);
        router.push(
          `/client/judicial-determination-of-rent?${searchParmas.toString()}`
        );
        setLoading(false);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const normalise = (value: number, MAX: number) => {
    let MIN = 0;
    let finalVal = ((value - MIN) * 100) / (MAX - MIN);
    if (finalVal > 100) {
      finalVal = 100;
    }
    return finalVal;
  };

  return (
    <ContentWrapper>
      <Box sx={{ width: "100%" }}>
        <div className="top-title">
          <h2 className="f-26 fw-400 mb-4 mt-5">
            Rent Dispute Assessment Form
          </h2>
        </div>
        <div className="create-cases mt-4">
          <div className="w-100 mr-1 linear-progress-p p-1 bg-white shadow ">
            <LinearProgress
              className="green-progress-bar"
              variant="determinate"
              value={normalise(progress, 100)}
            />
          </div>
          {loading ? (
            <div className="text-center mt-5">
              <CircularProgress />
            </div>
          ) : (
            <div>
              {
                <React.Fragment>
                  <div className="cases-active">
                    {progress === 10 && (
                      <div className="">
                        <PrivacyPolicy handleNext={handleNext} />
                      </div>
                    )}

                    {progress === 20 && (
                      <div className="eviction-forms">
                        <LeaseContractDetails data={rentData} hide={false} />
                      </div>
                    )}

                    {progress === 30 && (
                      <>
                        <div className=" eviction-forms ">
                          <LeaseClauses data={rentData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 40 && (
                      <>
                        <div className=" eviction-forms ">
                          <PremisesCharacteristics
                            data={rentData}
                            hide={false}
                          />
                        </div>
                      </>
                    )}
                    {progress === 50 && (
                      <>
                        <div className=" eviction-forms ">
                          <BuildingCharacteristics
                            data={rentData}
                            hide={false}
                          />
                        </div>
                      </>
                    )}

                    {progress === 60 && (
                      <>
                        <div className=" eviction-forms ">
                          <LocalityInformation data={rentData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 70 && (
                      <>
                        <div className=" eviction-forms ">
                          <PremisesExpertise data={rentData} hide={false} />
                          {/* <AddForm data={rentData} /> */}
                        </div>
                      </>
                    )}

                    {progress === 80 && (
                      <>
                        <div className=" eviction-forms ">
                          <RentAdjustment data={rentData} hide={false} />
                        </div>
                      </>
                    )}

                    {progress === 90 && (
                      <>
                        <div className=" eviction-forms ">
                          <Review data={rentData} />
                        </div>
                      </>
                    )}

                    {progress === 100 && (
                      <>
                        <div className=" eviction-forms ">
                          <ThankuStep />
                        </div>
                      </>
                    )}
                  </div>
                </React.Fragment>
              }
            </div>
          )}
        </div>
      </Box>
    </ContentWrapper>
  );
}
