import { PaginateData } from "@/types/Paginate";
import db from "@/utils/connectDB";
import { Metadata } from "next";
import React, { useEffect } from "react";
import "../../admin/admin.css";
import LawyerTypes from "@/models/lawyerTypes.model";
import { LawyerType } from "@/types/LawyerTypes";
import TypesTable from "./_typesTable";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default async function Lawyers() {
 
  return (
    <div className="main-content expert-cases">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">Lawyers List</h2>
        <Link href="/admin/lawyer-types/add">
          <button className="submit-btn rounded bg-white text-black">Add Lawyer Type</button>
        </Link>
      </div>
      <div className="res-table-box">
        <div className="table-responsive mt-4">
          <TypesTable />
        </div>
      </div>
    </div>
  );
}
