"use client";
import { Metadata } from "next";
import React, { useState } from "react";
import "react-quill/dist/quill.snow.css";
import "../../admin/admin.css";

import view from "@/assets/edit1.png";

import Image from "next/image";
import Table from "@/components/Table/Table";
import { useRouter } from "next/navigation";

export const metadata: Metadata = {
  title: "Terms&Conditions",
  description: "Generated by create next app",
};
type Content = {
  id: string;
  userType: string;
  type: string;
  Status: string;
};
const table: Content[] = [
  {
    id: "1",
    userType: "Client",
    type: "clientTerms",
    Status: "Active",
  },

  {
    id: "2",
    userType: "Expert",
    type: "expertTerms",
    Status: "Active",
  },
];
export default function Content() {
  const router = useRouter();
  const [page, setPage] = useState(1);

  return (
    <>
      <div className="bg-white rounded-lg mt-3">
        <div className="row p-4">
          <div className="col-6 md-6">
            <h5 className="bold">Content Management</h5>
          </div>
          <div className=" mt-3">
            <Table<Content>
              data={table ?? []}
              currentPage={1}
              totalEntries={10}
              handlePageChange={(e, page) => {
                setPage(page);
              }}
              columns={[                
                { title: "UserType", field: "userType" },
                {
                  field: "type",
                  title: "Action",
                  Cell({ entry: { type } }) {
                    return (
                      <span className="text-center">
                        <span
                          style={{ cursor: "pointer" }}
                          className="text-center w-25"
                          onClick={() =>
                            router.push(
                              `/admin/terms-conditions/terms/?type=${type}`
                            )
                          }
                        >
                          <Image
                            src={view}
                            alt=""
                            className="m-auto"
                            height={25}
                            width={25}
                          />
                        </span>
                      </span>
                    );
                  },
                },
              ]}
            />
          </div>
        </div>
      </div>
    </>
  );
}
