import React from "react";
import "../../client/client.css";

import { Button } from "@/components/Form/Button";

import { Metadata } from "next";
import { useRouter } from "next/navigation";
import ContentWrapper from "@/components/Layout/Client/ContentWrapper";
import Mandate from "./Mandate";

export const metadata: Metadata = {
  title: "Client/Financing",
  description: "Generated by create next app",
};

export default function MandatePage() {
  return <Mandate />;
}
