"use client";
import React, { useEffect, useState } from "react";
import { Metadata } from "next";
import "../../client/client.css";
import { Button } from "@/components/Form/Button";
import { CaseDetails } from "./_CaseDetails/CaseDetails";
import { MinorDetails } from "./_CaseDetails/MinorDetails";
import { PersonInfo } from "./_CaseDetails/PersonInfo";
import { CaseInfo } from "./_CaseDetails/CaseInfo";
import { FinancingStatus } from "../case-overview/_CaseComponents/FinancingStatus";
import { DocTracking } from "./_CaseDetails/DocTracking";
import { Query } from "./_CaseDetails/Query";
import { DocRequest } from "./_CaseDetails/DocRequest";
import { CircularProgress, Link } from "@mui/material";
import { DocRequestTrack } from "./_CaseDetails/DocRequestTrack";
import { Questioner } from "./_CaseDetails/Questioner";
import AssignedTask from "./_CaseDetails/AssignedTasks";
import { useSearchParams, useRouter } from "next/navigation";
import axios from "axios";
import { Cases } from "@/types/Cases";
import LoadingButton from "@mui/lab/LoadingButton";
import { useSession } from "next-auth/react";
import moment from "moment";
import { CompanyDetails } from "./_CaseDetails/CompanyDetails";
import { OpposingInfo } from "./_CaseDetails/OpposingInfo";

// export const metadata: Metadata = {
//   title: "Case Details",
//   description: "Generated by create next app",
// };

export default function CaseDetail() {
  const { data } = useSession();
  const session = data?.user;
  let params = useSearchParams();
  const router = useRouter();
  const id = params && params.get("id");
  const [loading, setLoading] = useState<boolean>(false);
  const [ExpertDetails, setExpert]: any = useState({});
  const [documents, setDocuments] = useState([]);
  const [Reports, setReports] = useState({ evaluation: "", financial: "" });
  const [filter, setFilter] = useState({ type: "all" });
  const [load, setLoad] = useState<boolean>(false);
  const [caseData, setCaseData] = useState<Cases>();
  const [DocsLoader, setDocsLoader] = useState(false);

  const GetexpertDetails = () => {
    axios
      .get("/api/expert/get")
      .then((res: any) => {
        console.log(res, "======resdata");
        if (res.data?.success) {
          setExpert(res?.data?.data);
        }
      })
      .catch((error) => {
        console.log(error);
      });
  };
  const GetEvalReport = () => {
    axios.get(`/api/cer-report/detail?case_id=${id}`).then((res: any) => {
      console.log(res, "data");
      setReports({ ...Reports, evaluation: res?.data?.data?.data });
    });
  };
  const GetDocuments = (type: any) => {
    setDocsLoader(true);
    setFilter({ ...filter, type: type });
    axios.get(`/api/cases/${id}/documents?type=${type}`).then((res: any) => {
      console.log(res, "data");
      setDocsLoader(false);

      setDocuments(res?.data?.data?.data);
    });
  };
  useEffect(() => {
    if (id) {
      getCaseById();
      GetDocuments("all");
      GetEvalReport();
    }
  }, [id, session]);
  const getCaseById = async () => {
    try {
      setLoading(true);
      if (id) {
        const { data } = await axios.get(
          `/api/client/case/get-case?caseId=${id}`
        );
        setCaseData(data?.data);
      }
      setLoading(false);
    } catch (error) {
      console.log("err", error);
      setLoading(false);
    }
  };
  return (
    <div className="main-content expert-cases details-litigation">
      <div className="top-br d-flex justify-content-between align-items-center">
        <h2 className="f-24">
          {/* {caseData?.caseType == "litigation" ? "Litigation" : "Pre Litigation"}  */}{" "}
          Case Details
        </h2>
        <LoadingButton
          loading={load}
          variant="contained"
          className="client-btn f-14 rounded-lg"
          size="large"
          onClick={() => {
            setLoad(true);
            router.back();
          }}
        >
          <span>Go Back</span>
        </LoadingButton>
      </div>

      {loading ? (
        <p className="text-center my-5">
          <CircularProgress />
        </p>
      ) : (
        <>
          <div className="cases-details-liti white-card rounded-lg mt-4 p-4">
            {/* <h4 className="f-18 bold">Case Details</h4> */}
            <div className="cases-liti bggray rounded-lg d-flex flex-wrap p-3">
              <p className="mb-0 f-14 d-flex gap-4 ">
                <span>Case Id :</span>
                <span className="semi-bold">#{caseData?.referenceId}</span>
              </p>
              <p className="mb-0 f-14 d-flex gap-4 ">
                <span>Client Name :</span>
                <span className="semi-bold">{caseData?.user?.firstName}</span>
              </p>
              <p className="mb-0 f-14 d-flex gap-4 ">
                <span>Registered on :</span>
                <span className="semi-bold">
                  {moment(caseData?.createdAt).format("Do MMMM YYYY")}
                </span>
              </p>
              <p className="mb-0 f-14 d-flex gap-4 ">
                <span>Case Status :</span>
                <span className="semi-bold text-capitalize">
                  {caseData?.status == "notResolved"
                    ? "Not Resolved"
                    : caseData?.status}
                </span>
              </p>

              <p className="mb-0 f-14 pt-3 d-flex gap-4 w-100 flex-wrap pre-liti-case">
                <span className="left-width">Case Description :</span>
                <span className="right-width semi-bold">
                  {caseData?.proceduralStatus?.briefDescription ?? "NA"}
                </span>
              </p>
            </div>
          </div>
          <div className="liti-minor-boxs row">
            <div className="col-12 col-md-8 mt-4">
              <div className="row">
                <div className="col-12 col-md-6">
                  <CaseDetails data={caseData} />
                </div>
                <div className="col-12 col-md-6">
                  {caseData?.groupInfo?.isSpouse == "yes" ? (
                    <MinorDetails data={caseData} />
                  ) : (
                    <CompanyDetails data={caseData} />
                  )}
                </div>
              </div>
              <div className="row">
                <div className="col-12 col-md-12 mt-4">
                  <FinancingStatus
                    user={data}
                    report={Reports}
                    data={caseData}
                  />
                </div>
                <div className="col-12 col-md-12 mt-4">
                  <DocTracking data={caseData} />
                </div>
              </div>
              <Questioner role={session?.role ?? ""} data={caseData} />
            </div>
            <div className="col-12 col-md-4 mt-4">
              {caseData?.groupInfo?.isRepresentative == "yes" ? (
                <PersonInfo data={caseData} />
              ) : (
                <OpposingInfo data={caseData} />
              )}
              <div className="case-personal-info mt-4">
                <CaseInfo data={caseData} />
              </div>
              {/* <div className="case-task-info mt-4">
            <AssignedTask />
          </div> */}
            </div>
          </div>
          <div className="comm-tools mt-4">
            <h3 className="f-18 semi-bold">Communication Tools</h3>
            <Query />
          </div>
          <div className="comm-tools req-tracking mt-4">
            <h3 className="f-18 semi-bold">Document Request Tracking</h3>
            <div className="res-tabs pt-4">
              <div className="res-tabs-box d-flex gap-3 align-items-center mb-4">
                <ul className="nav nav-tabs" id="myTab" role="tablist">
                  <li className="nav-item " role="presentation">
                    <button
                      className={`nav-link ${
                        filter?.type == "legal" ? "active" : ""
                      }`}
                      id="manager-tab"
                      data-bs-toggle="tab"
                      onClick={() => {
                        GetDocuments("legal");
                      }}
                      data-bs-target="#manager"
                      type="button"
                      role="tab"
                      aria-controls="manager"
                      aria-selected="false"
                    >
                      Case Manager{" "}
                    </button>
                  </li>
                  <li
                    className="nav-item"
                    style={{ marginLeft: "5px" }}
                    role="presentation"
                  >
                    <button
                      className={`nav-link ${
                        filter?.type == "all" ? "active" : ""
                      }`}
                      onClick={() => {
                        GetDocuments("all");
                      }}
                      id="manager-tab"
                      data-bs-toggle="tab"
                      data-bs-target="#manager"
                      type="button"
                      role="tab"
                      aria-controls="manager"
                      aria-selected="false"
                    >
                      On Behalf of other
                    </button>
                  </li>
                </ul>
              </div>
              <div className="tab-content" id="myTabContent">
                <div
                  className="tab-pane fade show active"
                  id="manager"
                  role="tabpanel"
                  aria-labelledby="manager-tab"
                >
                  <div className="doc-requets">
                    <div className="row">
                      {DocsLoader ? (
                        <>
                          <div
                            style={{ width: "40%" }}
                            className="card"
                            aria-hidden="true"
                          >
                            <div className="card-body">
                              <h5 className="card-title placeholder-glow">
                                <span className="placeholder col-6"></span>
                              </h5>
                              <p className="card-text placeholder-glow">
                                <span className="placeholder col-7"></span>
                                <span className="placeholder col-4"></span>
                                <span className="placeholder col-4"></span>
                                <span className="placeholder col-6"></span>
                                <span className="placeholder col-8"></span>
                              </p>
                              <a className="btn btn-primary disabled placeholder col-6"></a>
                            </div>
                          </div>
                          <div
                            style={{ width: "40%", marginLeft: "5px" }}
                            className="card"
                            aria-hidden="true"
                          >
                            <div className="card-body">
                              <h5 className="card-title placeholder-glow">
                                <span className="placeholder col-6"></span>
                              </h5>
                              <p className="card-text placeholder-glow">
                                <span className="placeholder col-7"></span>
                                <span className="placeholder col-4"></span>
                                <span className="placeholder col-4"></span>
                                <span className="placeholder col-6"></span>
                                <span className="placeholder col-8"></span>
                              </p>
                              <a className="btn btn-primary disabled placeholder col-6"></a>
                            </div>
                          </div>
                        </>
                      ) : (
                        <>
                          {documents?.map((itm: any, i: any) => {
                            return (
                              <div key={i} className="col-12 col-md-6">
                                <DocRequest data={itm} />
                              </div>
                            );
                          })}
                        </>
                      )}

                      {/* <div className="col-12 col-md-6">
                    <DocRequest />
                  </div> */}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
