import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Button } from "@/components/Form/Button";
import TaskTable from "./_TaskComponent/TaskTable";
import AddTask from "./_TaskComponent/AddTask";

export const metadata: Metadata = {
  title: "Task Assigned",
  description: "Generated by create next app",
};

export default function TaskAssigned() {

  return (
    <div className="main-content expert-cases case-members">
      <AddTask />
      <div className="res-table-box">
        <div className="mt-4">
          <TaskTable />
        </div>
      </div>
   
    </div>
  );
}
