import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import { Metadata } from "next";
import AnimateAuth from "@/components/Animate/AnimateAuth";
import Image from "next/image";
import logo from "@/assets/logo.png";
import "../login/login.css"
import loginbg from "@/assets/loginbg.png";
import female from "@/assets/female.png";
import OtpVerificationComponent from "./_otp-verify";

export const metadata: Metadata = {
  title: "Otp Verification",
  description: "Generated by create next app",
};

export default function OtpVerification() {
  return (
    <AnimateAuth>
      <section className="login-section">
        <div className="row login-main-r align-items-center">
          <div className="col-12 col-md-6 col-lg-6 relative">
          <div
              className="login-img  login-background  text-white relative "
              style={{
                backgroundImage: `url(${loginbg.src})`,
              }}
            >
              <Image src={logo} className="login-logo" alt="logo" />
              <h2 className="f-52 semi-bold pt-4">
                Empowering <br></br> Legal Solutions
              </h2>
              <p className="f-15">Join Our Tech-Driven Platform Today </p>
            </div>
            <div className="login-abs-icon">
              <Image src={female} className="female" alt="logo" />
            </div>
          </div>
          <div className="col-12 col-md-6 col-lg-6">
            <div className="login-form  p-5">
              <h2 className="bold f-52">Otp Verification</h2>
              <Card elevation={5} style={{ boxShadow: "none" }}>
                <CardContent className="p-0">
                  <OtpVerificationComponent />
                </CardContent>
              </Card>
             
                {/* <Typography className="mt-3 f-13" textAlign="center">
                No Account yet? 
                  <Link href="/auth/register" className="f-13 dark bold">
                    SIGN UP
                  </Link>
                </Typography>
              */}
            </div>
          </div>
        </div>
      </section>
    </AnimateAuth>
  );
}
