import React from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { LawyerImage } from "./_LawyerImage";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/Form/Button";

export const metadata: Metadata = {
  title: "Lawyer Information",
  description: "Generated by create next app",
};

export default function LawyerInformation() {
  return (
    <div className="main-content expert-dashboard">
      <div className="expert-profile client-profil">
        <div className="top-br">
          <h2 className="f-24 pb-3">Lawyer Information </h2>
        </div>
        <div className="row">
          <div className="col-12 col-md-7">
            <div className="prf-card-lawyer mb-4">
              <div className="white-card lawyer-info-card p-4">
                <div className="row">
                  <div className="col-12 col-md-4">
                    <div className="lawyer-info-icon text-center">
                      <LawyerImage />
                      <h5 className="f-18 semi-bold mt-3 mb-1">Mark Wilson</h5>
                      <h5 className="f-16 mb-1">mark@simmmple.com</h5>
                    </div>
                  </div>
                  <div className="col-12 col-md-8">
                    <div className="lawyer-profession">
                      <div className="profession-fles py-2 d-flex justify-content-between">
                        <span className="f-14 semi-bold">Full Name:</span>
                        <span className="f-14">Alec M. Thompson</span>
                      </div>
                      <div className="profession-fles  py-2 d-flex justify-content-between">
                        <span className="f-14 semi-bold">Legal Expertise:</span>
                        <span className="f-14">Family(Divorce) </span>
                      </div>
                      <div className="profession-fles  py-2 d-flex justify-content-between">
                        <span className="f-14 semi-bold">Location: </span>
                        <span className="f-14">United States </span>
                      </div>
                      <div className="profession-fles  py-2 d-flex justify-content-between">
                        <span className="f-14 semi-bold">
                          Languages Spoken:{" "}
                        </span>
                        <span className="f-14">
                          English | Spanish | French{" "}
                        </span>
                      </div>
                      <div className="profession-fles-about  py-2">
                        <span className="f-18 semi-bold d-block">
                          About Me:{" "}
                        </span>
                        <span className="f-14">
                          Contrary to popular belief, Lorem Ipsum is not simply
                          random text. It has roots in a piece of classical
                          Latin literature from 45 BC, making it over 2000 years
                          old. Richard McClintock,{" "}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="white-card lawyer-professional">
              <h3 className="f-24 semi-bold mb-0 p-3 border-btm">
                Professional
              </h3>
              <div className="proef-content">
                <div className="profession-fles-assign border-btm  p-3">
                  <span className="f-14 semi-bold d-block prf-left">
                    Professional Affiliations:{" "}
                  </span>
                  <span className="f-14 prf-right">Asia Leading Lawyer</span>
                </div>
                <div className="profession-fles-assign border-btm p-3">
                  <span className="f-14 semi-bold d-block prf-left">
                    Education:
                  </span>
                  <span className="f-14 prf-right">LLB (Bachelor of Laws)</span>
                </div>
                <div className="profession-fles-assign border-btm p-3">
                  <span className="f-14 semi-bold d-block prf-left">
                    Specializations:
                  </span>
                  <span className="f-14 prf-right">
                    Employment Law (Wage and Hour Disputes)
                  </span>
                </div>
                <div className="profession-fles-assign border-btm p-3">
                  <span className="f-14 semi-bold d-block prf-left">
                    Experience:
                  </span>
                  <span className="f-14 prf-right">10 years</span>
                </div>
                <div className="profession-fles-assign border-btm p-3">
                  <span className="f-14 semi-bold d-block prf-left">
                  Achievements/Awards:
                  </span>
                  <span className="f-14 prf-right">Brandeis Award | Antonio Hernández-Gil Young Lawyers Award | Brandeis Medal</span>
                </div>
              </div>
            </div>
          </div>
        </div>   
        
      </div>
      <div className="lawyer-info-buttons d-flex align-items-center gap-3  pt-4">
        <Button variant="contained" className="expert-btn">Assign</Button>
        <Button variant="outline" className="cancel-btn bg-white">Cancel</Button>
      </div>
    </div>
  );
}
