import React, { useState } from "react";
import { Metadata } from "next";
import "../../expert/expert.css";
import { Link } from "@mui/material";
import star from "@/assets/star.png";
import Image from "next/image";
import { Button } from "@/components/Form/Button";
import { TaskCalender } from "./_taskCalender";

export const metadata: Metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function TaskManagement() {
  return (
    <div className="main-content expert-cases case-members request-doc-upload">
      <div className="top-br d-flex justify-content-between align-items-center gap-3">
        <h2 className="f-24">Task Management</h2>
        <Button className="expert-btn" variant="contained">
          Send Reminder
        </Button>
      </div>
      <div className="row">
        <div className="col-12 col-md-8 mt-4 col-lg-9">
        <div className="schedule-task cal white-card p-4 mb-4">
            <TaskCalender />
        </div>
        </div>
        <div className="col-12 col-md-4 col-lg-3 mt-4">
          <div className="schedule-task white-card p-4 mb-4">
            <h4 className="f-18 semi-bold">12th October 2024</h4>
            <p className="f-14 bggray mb-0 p-3 rounded">Call Scheduled</p>
          </div>
          <div className="schedule-task white-card p-4 mb-4">
            <h4 className="f-18 semi-bold">14th October 2024</h4>
            <p className="f-14 bggray mb-0 p-3 rounded">Court Hearing</p>
          </div>
        </div>
      </div>
      <div className="row">
        <div className="col-12 col-md-6 mt-4">
          <div className="today-appoint import-dates white-card rounded-lg client-feedback">
            <div className="active-claims-box p-3">
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case ID</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">ED2312</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Type</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Client Name</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Jorge</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Category</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Task</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Date & Time</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Phone No.</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">+933442345</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Email</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">test@yopmail.com</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Status</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <span className="pending-status f-14">Start</span>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div className="col-12 col-md-6 mt-4">
          <div className="today-appoint import-dates white-card rounded-lg client-feedback">
            <div className="active-claims-box p-3">
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case ID</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">ED2312</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Type</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Client Name</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Jorge</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Case Category</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">Civil</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Task</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Date & Time</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">23 June 2024</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Phone No.</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">+933442345</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Email</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">test@yopmail.com</span>
              </div>
              <div className="d-flex active-claim-list">
                <span className="claim-status">Status</span>
                <span className="claim-coln">:</span>
                <span className="claim-status-cnt">
                  <span className="pending-status f-14">Start</span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
